/*
 * Copyright (C) 2025 UpbeatTech Inc. All Rights Reserved
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX short identifier: Apache-2.0
 */

#define SCU_SW_RESET_BOOT_REG          SCU_BOOTSTAT
#define SCU_SW_RESET_BOOT_POS          (12)
#define SCU_SW_RESET_BOOT_MSK          (0x1ul << SCU_SW_RESET_BOOT_POS)
#define SCU_WARM_BOOT_REG              SCU_BOOTSTAT
#define SCU_WARM_BOOT_POS              (11)
#define SCU_WARM_BOOT_MSK              (0x1ul << SCU_WARM_BOOT_POS)
#define SCU_WDT_RESET_REG              SCU_BOOTSTAT
#define SCU_WDT_RESET_POS              (10)
#define SCU_WDT_RESET_MSK              (0x1ul << SCU_WDT_RESET_POS)
#define SCU_TICK_BOOTUP_REG            SCU_BOOTSTAT
#define SCU_TICK_BOOTUP_POS            (9)
#define SCU_TICK_BOOTUP_MSK            (0x1ul << SCU_TICK_BOOTUP_POS)
#define SCU_RTC_BOOTUP_REG             SCU_BOOTSTAT
#define SCU_RTC_BOOTUP_POS             (8)
#define SCU_RTC_BOOTUP_MSK             (0x1ul << SCU_RTC_BOOTUP_POS)
#define SCU_GPIO_BOOTUP_REG            SCU_BOOTSTAT
#define SCU_GPIO_BOOTUP_POS            (4)
#define SCU_GPIO_BOOTUP_MSK            (0xFul << SCU_GPIO_BOOTUP_POS)
#define SCU_HW_RESET_REG               SCU_BOOTSTAT
#define SCU_HW_RESET_POS               (3)
#define SCU_HW_RESET_MSK               (0x1ul << SCU_HW_RESET_POS)
#define SCU_E34_ECC_RESET_REG          SCU_BOOTSTAT
#define SCU_E34_ECC_RESET_POS          (2)
#define SCU_E34_ECC_RESET_MSK          (0x1ul << SCU_E34_ECC_RESET_POS)
#define SCU_E21_ECC_RESET_REG          SCU_BOOTSTAT
#define SCU_E21_ECC_RESET_POS          (1)
#define SCU_E21_ECC_RESET_MSK          (0x1ul << SCU_E21_ECC_RESET_POS)
#define SCU_POWERON_BOOT_REG           SCU_BOOTSTAT
#define SCU_POWERON_BOOT_POS           (0)
#define SCU_POWERON_BOOT_MSK           (0x1ul << SCU_POWERON_BOOT_POS)
#define SCU_SW_RESET_EN_REG            SCU_BOOTEN
#define SCU_SW_RESET_EN_POS            (12)
#define SCU_SW_RESET_EN_MSK            (0x1ul << SCU_SW_RESET_EN_POS)
#define SCU_WARM_BOOT_EN_REG           SCU_BOOTEN
#define SCU_WARM_BOOT_EN_POS           (11)
#define SCU_WARM_BOOT_EN_MSK           (0x1ul << SCU_WARM_BOOT_EN_POS)
#define SCU_WDT_RESET_EN_REG           SCU_BOOTEN
#define SCU_WDT_RESET_EN_POS           (10)
#define SCU_WDT_RESET_EN_MSK           (0x1ul << SCU_WDT_RESET_EN_POS)
#define SCU_TICK_BOOTUP_EN_REG         SCU_BOOTEN
#define SCU_TICK_BOOTUP_EN_POS         (9)
#define SCU_TICK_BOOTUP_EN_MSK         (0x1ul << SCU_TICK_BOOTUP_EN_POS)
#define SCU_RTC_BOOTUP_EN_REG          SCU_BOOTEN
#define SCU_RTC_BOOTUP_EN_POS          (8)
#define SCU_RTC_BOOTUP_EN_MSK          (0x1ul << SCU_RTC_BOOTUP_EN_POS)
#define SCU_GPIO_BOOTUP_EN_REG         SCU_BOOTEN
#define SCU_GPIO_BOOTUP_EN_POS         (4)
#define SCU_GPIO_BOOTUP_EN_MSK         (0xFul << SCU_GPIO_BOOTUP_EN_POS)
#define SCU_E34_ECC_RESET_EN_REG       SCU_BOOTEN
#define SCU_E34_ECC_RESET_EN_POS       (2)
#define SCU_E34_ECC_RESET_EN_MSK       (0x1ul << SCU_E34_ECC_RESET_EN_POS)
#define SCU_E21_ECC_RESET_EN_REG       SCU_BOOTEN
#define SCU_E21_ECC_RESET_EN_POS       (1)
#define SCU_E21_ECC_RESET_EN_MSK       (0x1ul << SCU_E21_ECC_RESET_EN_POS)
#define SCU_POWER_OK_WAIT_REG          SCU_POKWAIT
#define SCU_POWER_OK_WAIT_POS          (0)
#define SCU_POWER_OK_WAIT_MSK          (0xFFFFul << SCU_POWER_OK_WAIT_POS)
#define SCU_GPIO_PWRCTRL_WAIT_REG      SCU_GPCWAIT
#define SCU_GPIO_PWRCTRL_WAIT_POS      (0)
#define SCU_GPIO_PWRCTRL_WAIT_MSK      (0xFFFFul << SCU_GPIO_PWRCTRL_WAIT_POS)
#define SCU_RTC_INT_STAT_REG           SCU_RTCMIS
#define SCU_RTC_INT_STAT_POS           (4)
#define SCU_RTC_INT_STAT_MSK           (0x1ul << SCU_RTC_INT_STAT_POS)
#define SCU_RTCM_GPIO_INT_STAT_REG     SCU_RTCMIS
#define SCU_RTCM_GPIO_INT_STAT_POS     (0)
#define SCU_RTCM_GPIO_INT_STAT_MSK     (0xFul << SCU_RTCM_GPIO_INT_STAT_POS)
#define SCU_RTC_INT_STATR_REG          SCU_RTCMRIS
#define SCU_RTC_INT_STATR_POS          (4)
#define SCU_RTC_INT_STATR_MSK          (0x1ul << SCU_RTC_INT_STATR_POS)
#define SCU_RTCM_GPIO_INT_STATR_REG    SCU_RTCMRIS
#define SCU_RTCM_GPIO_INT_STATR_POS    (0)
#define SCU_RTCM_GPIO_INT_STATR_MSK    (0xFul << SCU_RTCM_GPIO_INT_STATR_POS)
#define SCU_RTC_INT_EN_REG             SCU_RTCMIE
#define SCU_RTC_INT_EN_POS             (4)
#define SCU_RTC_INT_EN_MSK             (0x1ul << SCU_RTC_INT_EN_POS)
#define SCU_RTCM_GPIO_INT_EN_REG       SCU_RTCMIE
#define SCU_RTCM_GPIO_INT_EN_POS       (0)
#define SCU_RTCM_GPIO_INT_EN_MSK       (0xFul << SCU_RTCM_GPIO_INT_EN_POS)
#define SCU_GPIO_PWRCTRL_EN_REG        SCU_RTCMCTRL
#define SCU_GPIO_PWRCTRL_EN_POS        (3)
#define SCU_GPIO_PWRCTRL_EN_MSK        (0x1ul << SCU_GPIO_PWRCTRL_EN_POS)
#define SCU_XIP_IO_RET_EN_REG          SCU_RTCMCTRL
#define SCU_XIP_IO_RET_EN_POS          (2)
#define SCU_XIP_IO_RET_EN_MSK          (0x1ul << SCU_XIP_IO_RET_EN_POS)
#define SCU_NAON_IO_RET_EN_REG         SCU_RTCMCTRL
#define SCU_NAON_IO_RET_EN_POS         (1)
#define SCU_NAON_IO_RET_EN_MSK         (0x1ul << SCU_NAON_IO_RET_EN_POS)
#define SCU_AON_IO_RET_EN_REG          SCU_RTCMCTRL
#define SCU_AON_IO_RET_EN_POS          (0)
#define SCU_AON_IO_RET_EN_MSK          (0x1ul << SCU_AON_IO_RET_EN_POS)
#define SCU_RTCM_GPIO3_CTRL_REG        SCU_RTCMGPCTRL0
#define SCU_RTCM_GPIO3_CTRL_POS        (24)
#define SCU_RTCM_GPIO3_CTRL_MSK        (0xFFul << SCU_RTCM_GPIO3_CTRL_POS)
#define SCU_RTCM_GPIO2_CTRL_REG        SCU_RTCMGPCTRL0
#define SCU_RTCM_GPIO2_CTRL_POS        (16)
#define SCU_RTCM_GPIO2_CTRL_MSK        (0xFFul << SCU_RTCM_GPIO2_CTRL_POS)
#define SCU_RTCM_GPIO1_CTRL_REG        SCU_RTCMGPCTRL0
#define SCU_RTCM_GPIO1_CTRL_POS        (8)
#define SCU_RTCM_GPIO1_CTRL_MSK        (0xFFul << SCU_RTCM_GPIO1_CTRL_POS)
#define SCU_RTCM_GPIO0_CTRL_REG        SCU_RTCMGPCTRL0
#define SCU_RTCM_GPIO0_CTRL_POS        (0)
#define SCU_RTCM_GPIO0_CTRL_MSK        (0xFFul << SCU_RTCM_GPIO0_CTRL_POS)
#define SCU_RTCM_GPIO_DEBOUNCE_REG     SCU_RTCMGPCTRL1
#define SCU_RTCM_GPIO_DEBOUNCE_POS     (0)
#define SCU_RTCM_GPIO_DEBOUNCE_MSK     (0x3FFul << SCU_RTCM_GPIO_DEBOUNCE_POS)
#define SCU_RTCM_CLK_EN_REG            SCU_RTCMCLKEN
#define SCU_RTCM_CLK_EN_POS            (0)
#define SCU_RTCM_CLK_EN_MSK            (0xFFul << SCU_RTCM_CLK_EN_POS)
#define SCU_RTCM_PAD_CTRL3_REG         SCU_RTCMPADCTRL
#define SCU_RTCM_PAD_CTRL3_POS         (24)
#define SCU_RTCM_PAD_CTRL3_MSK         (0xFFul << SCU_RTCM_PAD_CTRL3_POS)
#define SCU_RTCM_PAD_CTRL2_REG         SCU_RTCMPADCTRL
#define SCU_RTCM_PAD_CTRL2_POS         (16)
#define SCU_RTCM_PAD_CTRL2_MSK         (0xFFul << SCU_RTCM_PAD_CTRL2_POS)
#define SCU_RTCM_PAD_CTRL1_REG         SCU_RTCMPADCTRL
#define SCU_RTCM_PAD_CTRL1_POS         (8)
#define SCU_RTCM_PAD_CTRL1_MSK         (0xFFul << SCU_RTCM_PAD_CTRL1_POS)
#define SCU_RTCM_PAD_CTRL0_REG         SCU_RTCMPADCTRL
#define SCU_RTCM_PAD_CTRL0_POS         (0)
#define SCU_RTCM_PAD_CTRL0_MSK         (0xFFul << SCU_RTCM_PAD_CTRL0_POS)
#define SCU_RTCM_MAILBOX0_REG          SCU_RTCMMB0
#define SCU_RTCM_MAILBOX0_POS          (0)
#define SCU_RTCM_MAILBOX0_MSK          (0xFFFFFFFFul << SCU_RTCM_MAILBOX0_POS)
#define SCU_RTCM_MAILBOX1_REG          SCU_RTCMMB1
#define SCU_RTCM_MAILBOX1_POS          (0)
#define SCU_RTCM_MAILBOX1_MSK          (0xFFFFFFFFul << SCU_RTCM_MAILBOX1_POS)
#define SCU_RTCM_MAILBOX2_REG          SCU_RTCMMB2
#define SCU_RTCM_MAILBOX2_POS          (0)
#define SCU_RTCM_MAILBOX2_MSK          (0xFFFFFFFFul << SCU_RTCM_MAILBOX2_POS)
#define SCU_RTCM_MAILBOX3_REG          SCU_RTCMMB3
#define SCU_RTCM_MAILBOX3_POS          (0)
#define SCU_RTCM_MAILBOX3_MSK          (0xFFFFFFFFul << SCU_RTCM_MAILBOX3_POS)
#define SCU_RTC_CSE_REG                SCU_RTCCTRL
#define SCU_RTC_CSE_POS                (0)
#define SCU_RTC_CSE_MSK                (0x1ul << SCU_RTC_CSE_POS)
#define SCU_T_RTCM_INT_REG             SCU_RTCMISTEST
#define SCU_T_RTCM_INT_POS             (0)
#define SCU_T_RTCM_INT_MSK             (0x1Ful << SCU_T_RTCM_INT_POS)
#define SCU_T_RTCM_INT_EN_REG          SCU_RTCMISTESTEN
#define SCU_T_RTCM_INT_EN_POS          (0)
#define SCU_T_RTCM_INT_EN_MSK          (0x1ul << SCU_T_RTCM_INT_EN_POS)
#define SCU_T_SEQ_CODE_REG             SCU_POWERMODE
#define SCU_T_SEQ_CODE_POS             (8)
#define SCU_T_SEQ_CODE_MSK             (0xFFul << SCU_T_SEQ_CODE_POS)
#define SCU_T_RUN_SEQUENCE_REG         SCU_POWERMODE
#define SCU_T_RUN_SEQUENCE_POS         (5)
#define SCU_T_RUN_SEQUENCE_MSK         (0x1ul << SCU_T_RUN_SEQUENCE_POS)
#define SCU_T_POWER_MODE_REG           SCU_POWERMODE
#define SCU_T_POWER_MODE_POS           (0)
#define SCU_T_POWER_MODE_MSK           (0xFul << SCU_T_POWER_MODE_POS)
#define SCU_HW_VERSION_REG             SCU_HWVERSION
#define SCU_HW_VERSION_POS             (0)
#define SCU_HW_VERSION_MSK             (0xFFul << SCU_HW_VERSION_POS)
#define SCU_JTAG_STRAP_REG             SCU_HWSTRAP
#define SCU_JTAG_STRAP_POS             (4)
#define SCU_JTAG_STRAP_MSK             (0x1ul << SCU_JTAG_STRAP_POS)
#define SCU_UART_STRAP_REG             SCU_HWSTRAP
#define SCU_UART_STRAP_POS             (2)
#define SCU_UART_STRAP_MSK             (0x3ul << SCU_UART_STRAP_POS)
#define SCU_REMAP_STRAP_REG            SCU_HWSTRAP
#define SCU_REMAP_STRAP_POS            (0)
#define SCU_REMAP_STRAP_MSK            (0x3ul << SCU_REMAP_STRAP_POS)
#define SCU_EXREG_RESET_MSK_REG        SCU_RBTCONF
#define SCU_EXREG_RESET_MSK_POS        (2)
#define SCU_EXREG_RESET_MSK_MSK        (0x1ul << SCU_EXREG_RESET_MSK_POS)
#define SCU_SW_REMAP_REG               SCU_RBTCONF
#define SCU_SW_REMAP_POS               (0)
#define SCU_SW_REMAP_MSK               (0x3ul << SCU_SW_REMAP_POS)
#define SCU_X_PKG_REG                  SCU_PKG
#define SCU_X_PKG_POS                  (0)
#define SCU_X_PKG_MSK                  (0x1ul << SCU_X_PKG_POS)
#define SCU_T_AON_SEQ_CODE_REG         SCU_AONPOWERMODE
#define SCU_T_AON_SEQ_CODE_POS         (8)
#define SCU_T_AON_SEQ_CODE_MSK         (0xFFul << SCU_T_AON_SEQ_CODE_POS)
#define SCU_T_AON_RUN_SEQUENCE_REG     SCU_AONPOWERMODE
#define SCU_T_AON_RUN_SEQUENCE_POS     (5)
#define SCU_T_AON_RUN_SEQUENCE_MSK     (0x1ul << SCU_T_AON_RUN_SEQUENCE_POS)
#define SCU_T_AON_POWER_MODE_REG       SCU_AONPOWERMODE
#define SCU_T_AON_POWER_MODE_POS       (0)
#define SCU_T_AON_POWER_MODE_MSK       (0xFul << SCU_T_AON_POWER_MODE_POS)
#define SCU_MANUFACTURER_REG           SCU_OTPAUTOLD0
#define SCU_MANUFACTURER_POS           (16)
#define SCU_MANUFACTURER_MSK           (0xFFFFul << SCU_MANUFACTURER_POS)
#define SCU_CHIP_ID_REG                SCU_OTPAUTOLD0
#define SCU_CHIP_ID_POS                (4)
#define SCU_CHIP_ID_MSK                (0xFFFul << SCU_CHIP_ID_POS)
#define SCU_VERSION_REG                SCU_OTPAUTOLD0
#define SCU_VERSION_POS                (0)
#define SCU_VERSION_MSK                (0xFul << SCU_VERSION_POS)
#define SCU_LOT_NUMBER_REG             SCU_OTPAUTOLD1
#define SCU_LOT_NUMBER_POS             (19)
#define SCU_LOT_NUMBER_MSK             (0x1FFFul << SCU_LOT_NUMBER_POS)
#define SCU_WAFER_NUMBER_REG           SCU_OTPAUTOLD1
#define SCU_WAFER_NUMBER_POS           (14)
#define SCU_WAFER_NUMBER_MSK           (0x1Ful << SCU_WAFER_NUMBER_POS)
#define SCU_DIE_X_REG                  SCU_OTPAUTOLD1
#define SCU_DIE_X_POS                  (7)
#define SCU_DIE_X_MSK                  (0x7Ful << SCU_DIE_X_POS)
#define SCU_DIE_Y_REG                  SCU_OTPAUTOLD1
#define SCU_DIE_Y_POS                  (0)
#define SCU_DIE_Y_MSK                  (0x7Ful << SCU_DIE_Y_POS)
#define SCU_OTP_RSVD1_REG              SCU_OTPAUTOLD2
#define SCU_OTP_RSVD1_POS              (16)
#define SCU_OTP_RSVD1_MSK              (0xFFFFul << SCU_OTP_RSVD1_POS)
#define SCU_JTAG_PW_REG                SCU_OTPAUTOLD2
#define SCU_JTAG_PW_POS                (0)
#define SCU_JTAG_PW_MSK                (0xFFFFul << SCU_JTAG_PW_POS)
#define SCU_OTP_UDL_CONFIG_REG         SCU_OTPAUTOLD3
#define SCU_OTP_UDL_CONFIG_POS         (30)
#define SCU_OTP_UDL_CONFIG_MSK         (0x3ul << SCU_OTP_UDL_CONFIG_POS)
#define SCU_OTP_UDL1_REG               SCU_OTPAUTOLD3
#define SCU_OTP_UDL1_POS               (27)
#define SCU_OTP_UDL1_MSK               (0x7ul << SCU_OTP_UDL1_POS)
#define SCU_OTP_UDL2_REG               SCU_OTPAUTOLD3
#define SCU_OTP_UDL2_POS               (24)
#define SCU_OTP_UDL2_MSK               (0x7ul << SCU_OTP_UDL2_POS)
#define SCU_OTP_SECURE_CONFIG_REG      SCU_OTPAUTOLD3
#define SCU_OTP_SECURE_CONFIG_POS      (20)
#define SCU_OTP_SECURE_CONFIG_MSK      (0xFul << SCU_OTP_SECURE_CONFIG_POS)
#define SCU_OTP_SECURE_HASH_ALGO_REG   SCU_OTPAUTOLD3
#define SCU_OTP_SECURE_HASH_ALGO_POS   (18)
#define SCU_OTP_SECURE_HASH_ALGO_MSK   (0x3ul << SCU_OTP_SECURE_HASH_ALGO_POS)
#define SCU_OTP_SECURE_HASH_EN_REG     SCU_OTPAUTOLD3
#define SCU_OTP_SECURE_HASH_EN_POS     (17)
#define SCU_OTP_SECURE_HASH_EN_MSK     (0x1ul << SCU_OTP_SECURE_HASH_EN_POS)
#define SCU_OTP_SECURE_BOOT_REG        SCU_OTPAUTOLD3
#define SCU_OTP_SECURE_BOOT_POS        (16)
#define SCU_OTP_SECURE_BOOT_MSK        (0x1ul << SCU_OTP_SECURE_BOOT_POS)
#define SCU_OTP_RSVD3_REG              SCU_OTPAUTOLD3
#define SCU_OTP_RSVD3_POS              (14)
#define SCU_OTP_RSVD3_MSK              (0x3ul << SCU_OTP_RSVD3_POS)
#define SCU_OTP_SWREMAP_LOCK_REG       SCU_OTPAUTOLD3
#define SCU_OTP_SWREMAP_LOCK_POS       (13)
#define SCU_OTP_SWREMAP_LOCK_MSK       (0x1ul << SCU_OTP_SWREMAP_LOCK_POS)
#define SCU_OTP_REMAP_LOCK_REG         SCU_OTPAUTOLD3
#define SCU_OTP_REMAP_LOCK_POS         (12)
#define SCU_OTP_REMAP_LOCK_MSK         (0x1ul << SCU_OTP_REMAP_LOCK_POS)
#define SCU_OTP_RSVD2_REG              SCU_OTPAUTOLD3
#define SCU_OTP_RSVD2_POS              (0)
#define SCU_OTP_RSVD2_MSK              (0xFFFul << SCU_OTP_RSVD2_POS)
#define SCU_SW_TO_E21_INT_STAT_REG     SCU_AONIS
#define SCU_SW_TO_E21_INT_STAT_POS     (5)
#define SCU_SW_TO_E21_INT_STAT_MSK     (0x1ul << SCU_SW_TO_E21_INT_STAT_POS)
#define SCU_LEAVE_LURKING_INT_STAT_REG SCU_AONIS
#define SCU_LEAVE_LURKING_INT_STAT_POS (3)
#define SCU_LEAVE_LURKING_INT_STAT_MSK (0x1ul << SCU_LEAVE_LURKING_INT_STAT_POS)
#define SCU_ENTER_LURKING_INT_STAT_REG SCU_AONIS
#define SCU_ENTER_LURKING_INT_STAT_POS (2)
#define SCU_ENTER_LURKING_INT_STAT_MSK (0x1ul << SCU_ENTER_LURKING_INT_STAT_POS)
#define SCU_LEAVE_SLEEP_INT_STAT_REG   SCU_AONIS
#define SCU_LEAVE_SLEEP_INT_STAT_POS   (1)
#define SCU_LEAVE_SLEEP_INT_STAT_MSK   (0x1ul << SCU_LEAVE_SLEEP_INT_STAT_POS)
#define SCU_ENTER_SLEEP_INT_STAT_REG   SCU_AONIS
#define SCU_ENTER_SLEEP_INT_STAT_POS   (0)
#define SCU_ENTER_SLEEP_INT_STAT_MSK   (0x1ul << SCU_ENTER_SLEEP_INT_STAT_POS)
#define SCU_SW_TO_E21_INT_STATR_REG    SCU_AONRIS
#define SCU_SW_TO_E21_INT_STATR_POS    (5)
#define SCU_SW_TO_E21_INT_STATR_MSK    (0x1ul << SCU_SW_TO_E21_INT_STATR_POS)
#define SCU_LEAVE_LURKING_INT_STATR_REG SCU_AONRIS
#define SCU_LEAVE_LURKING_INT_STATR_POS (3)
#define SCU_LEAVE_LURKING_INT_STATR_MSK (0x1ul << SCU_LEAVE_LURKING_INT_STATR_POS)
#define SCU_ENTER_LURKING_INT_STATR_REG SCU_AONRIS
#define SCU_ENTER_LURKING_INT_STATR_POS (2)
#define SCU_ENTER_LURKING_INT_STATR_MSK (0x1ul << SCU_ENTER_LURKING_INT_STATR_POS)
#define SCU_LEAVE_SLEEP_INT_STATR_REG  SCU_AONRIS
#define SCU_LEAVE_SLEEP_INT_STATR_POS  (1)
#define SCU_LEAVE_SLEEP_INT_STATR_MSK  (0x1ul << SCU_LEAVE_SLEEP_INT_STATR_POS)
#define SCU_ENTER_SLEEP_INT_STATR_REG  SCU_AONRIS
#define SCU_ENTER_SLEEP_INT_STATR_POS  (0)
#define SCU_ENTER_SLEEP_INT_STATR_MSK  (0x1ul << SCU_ENTER_SLEEP_INT_STATR_POS)
#define SCU_SW_TO_E21_INT_EN_REG       SCU_AONIE
#define SCU_SW_TO_E21_INT_EN_POS       (5)
#define SCU_SW_TO_E21_INT_EN_MSK       (0x1ul << SCU_SW_TO_E21_INT_EN_POS)
#define SCU_LEAVE_LURKING_INT_EN_REG   SCU_AONIE
#define SCU_LEAVE_LURKING_INT_EN_POS   (3)
#define SCU_LEAVE_LURKING_INT_EN_MSK   (0x1ul << SCU_LEAVE_LURKING_INT_EN_POS)
#define SCU_ENTER_LURKING_INT_EN_REG   SCU_AONIE
#define SCU_ENTER_LURKING_INT_EN_POS   (2)
#define SCU_ENTER_LURKING_INT_EN_MSK   (0x1ul << SCU_ENTER_LURKING_INT_EN_POS)
#define SCU_LEAVE_SLEEP_INT_EN_REG     SCU_AONIE
#define SCU_LEAVE_SLEEP_INT_EN_POS     (1)
#define SCU_LEAVE_SLEEP_INT_EN_MSK     (0x1ul << SCU_LEAVE_SLEEP_INT_EN_POS)
#define SCU_ENTER_SLEEP_INT_EN_REG     SCU_AONIE
#define SCU_ENTER_SLEEP_INT_EN_POS     (0)
#define SCU_ENTER_SLEEP_INT_EN_MSK     (0x1ul << SCU_ENTER_SLEEP_INT_EN_POS)
#define SCU_LEAVE_LURKING_REG          SCU_AONCTRL
#define SCU_LEAVE_LURKING_POS          (3)
#define SCU_LEAVE_LURKING_MSK          (0x1ul << SCU_LEAVE_LURKING_POS)
#define SCU_ENTER_LURKING_REG          SCU_AONCTRL
#define SCU_ENTER_LURKING_POS          (2)
#define SCU_ENTER_LURKING_MSK          (0x1ul << SCU_ENTER_LURKING_POS)
#define SCU_LEAVE_SLEEP_REG            SCU_AONCTRL
#define SCU_LEAVE_SLEEP_POS            (1)
#define SCU_LEAVE_SLEEP_MSK            (0x1ul << SCU_LEAVE_SLEEP_POS)
#define SCU_SIF_EVENT_MSK_REG          SCU_PMICCTRL
#define SCU_SIF_EVENT_MSK_POS          (12)
#define SCU_SIF_EVENT_MSK_MSK          (0x1Ful << SCU_SIF_EVENT_MSK_POS)
#define SCU_PMIC_CTRL_PRESET_REG       SCU_PMICCTRL
#define SCU_PMIC_CTRL_PRESET_POS       (8)
#define SCU_PMIC_CTRL_PRESET_MSK       (0x7ul << SCU_PMIC_CTRL_PRESET_POS)
#define SCU_PMIC_CTRL_VALUE_REG        SCU_PMICCTRL
#define SCU_PMIC_CTRL_VALUE_POS        (4)
#define SCU_PMIC_CTRL_VALUE_MSK        (0x7ul << SCU_PMIC_CTRL_VALUE_POS)
#define SCU_SET_PMIC_SIF_REG           SCU_PMICCTRL
#define SCU_SET_PMIC_SIF_POS           (3)
#define SCU_SET_PMIC_SIF_MSK           (0x1ul << SCU_SET_PMIC_SIF_POS)
#define SCU_SET_PMIC_GPIO_REG          SCU_PMICCTRL
#define SCU_SET_PMIC_GPIO_POS          (2)
#define SCU_SET_PMIC_GPIO_MSK          (0x1ul << SCU_SET_PMIC_GPIO_POS)
#define SCU_SWITCH_GPIO_SIF_REG        SCU_PMICCTRL
#define SCU_SWITCH_GPIO_SIF_POS        (1)
#define SCU_SWITCH_GPIO_SIF_MSK        (0x1ul << SCU_SWITCH_GPIO_SIF_POS)
#define SCU_SET_PMIC_UP_REG            SCU_PMICCTRL
#define SCU_SET_PMIC_UP_POS            (0)
#define SCU_SET_PMIC_UP_MSK            (0x1ul << SCU_SET_PMIC_UP_POS)
#define SCU_E34_ECC_2BIT_OBS_REG       SCU_E34CTRL
#define SCU_E34_ECC_2BIT_OBS_POS       (3)
#define SCU_E34_ECC_2BIT_OBS_MSK       (0x1ul << SCU_E34_ECC_2BIT_OBS_POS)
#define SCU_E34_WFI_OBS_REG            SCU_E34CTRL
#define SCU_E34_WFI_OBS_POS            (2)
#define SCU_E34_WFI_OBS_MSK            (0x1ul << SCU_E34_WFI_OBS_POS)
#define SCU_SW_TO_E34_INT_REG          SCU_E34CTRL
#define SCU_SW_TO_E34_INT_POS          (0)
#define SCU_SW_TO_E34_INT_MSK          (0x1ul << SCU_SW_TO_E34_INT_POS)
#define SCU_RCOSC_FREQ_SEL_CH5_OBS_REG SCU_RCOSCTRIM
#define SCU_RCOSC_FREQ_SEL_CH5_OBS_POS (30)
#define SCU_RCOSC_FREQ_SEL_CH5_OBS_MSK (0x3ul << SCU_RCOSC_FREQ_SEL_CH5_OBS_POS)
#define SCU_RCOSC_FREQ_SEL_CH4_OBS_REG SCU_RCOSCTRIM
#define SCU_RCOSC_FREQ_SEL_CH4_OBS_POS (28)
#define SCU_RCOSC_FREQ_SEL_CH4_OBS_MSK (0x3ul << SCU_RCOSC_FREQ_SEL_CH4_OBS_POS)
#define SCU_RCOSC_AUTOTRIM_EN_REG      SCU_RCOSCTRIM
#define SCU_RCOSC_AUTOTRIM_EN_POS      (27)
#define SCU_RCOSC_AUTOTRIM_EN_MSK      (0x1ul << SCU_RCOSC_AUTOTRIM_EN_POS)
#define SCU_RCOSC_AUTOTRIM_UP_REG      SCU_RCOSCTRIM
#define SCU_RCOSC_AUTOTRIM_UP_POS      (18)
#define SCU_RCOSC_AUTOTRIM_UP_MSK      (0x1FFul << SCU_RCOSC_AUTOTRIM_UP_POS)
#define SCU_RCOSC_AUTOTRIM_LO_REG      SCU_RCOSCTRIM
#define SCU_RCOSC_AUTOTRIM_LO_POS      (9)
#define SCU_RCOSC_AUTOTRIM_LO_MSK      (0x1FFul << SCU_RCOSC_AUTOTRIM_LO_POS)
#define SCU_RCOSC_TRIM_COUNT_REG       SCU_RCOSCTRIM
#define SCU_RCOSC_TRIM_COUNT_POS       (0)
#define SCU_RCOSC_TRIM_COUNT_MSK       (0x1FFul << SCU_RCOSC_TRIM_COUNT_POS)
#define SCU_RCOSC_PTRIM_REG            SCU_RCOSCCTRL
#define SCU_RCOSC_PTRIM_POS            (24)
#define SCU_RCOSC_PTRIM_MSK            (0xFFul << SCU_RCOSC_PTRIM_POS)
#define SCU_RCOSC_PTRIM_VALUE_REG      SCU_RCOSCCTRL
#define SCU_RCOSC_PTRIM_VALUE_POS      (16)
#define SCU_RCOSC_PTRIM_VALUE_MSK      (0xFFul << SCU_RCOSC_PTRIM_VALUE_POS)
#define SCU_RCOSC_TRIM_VALUE_REG       SCU_RCOSCCTRL
#define SCU_RCOSC_TRIM_VALUE_POS       (12)
#define SCU_RCOSC_TRIM_VALUE_MSK       (0xFul << SCU_RCOSC_TRIM_VALUE_POS)
#define SCU_RCOSC_COUNT_START_REG      SCU_RCOSCCTRL
#define SCU_RCOSC_COUNT_START_POS      (9)
#define SCU_RCOSC_COUNT_START_MSK      (0x1ul << SCU_RCOSC_COUNT_START_POS)
#define SCU_RCOSC_FREQ_SEL_CH5_REG     SCU_RCOSCCTRL
#define SCU_RCOSC_FREQ_SEL_CH5_POS     (6)
#define SCU_RCOSC_FREQ_SEL_CH5_MSK     (0x3ul << SCU_RCOSC_FREQ_SEL_CH5_POS)
#define SCU_RCOSC_FREQ_SEL_CH4_REG     SCU_RCOSCCTRL
#define SCU_RCOSC_FREQ_SEL_CH4_POS     (4)
#define SCU_RCOSC_FREQ_SEL_CH4_MSK     (0x3ul << SCU_RCOSC_FREQ_SEL_CH4_POS)
#define SCU_RCOSC_ENB_CH5_REG          SCU_RCOSCCTRL
#define SCU_RCOSC_ENB_CH5_POS          (3)
#define SCU_RCOSC_ENB_CH5_MSK          (0x1ul << SCU_RCOSC_ENB_CH5_POS)
#define SCU_RCOSC_ENB_CH4_REG          SCU_RCOSCCTRL
#define SCU_RCOSC_ENB_CH4_POS          (2)
#define SCU_RCOSC_ENB_CH4_MSK          (0x1ul << SCU_RCOSC_ENB_CH4_POS)
#define SCU_RCOSC_TRIM_EN_REG          SCU_RCOSCCTRL
#define SCU_RCOSC_TRIM_EN_POS          (1)
#define SCU_RCOSC_TRIM_EN_MSK          (0x1ul << SCU_RCOSC_TRIM_EN_POS)
#define SCU_RCOSC_DIS_L0_REG           SCU_RCOSCCTRL
#define SCU_RCOSC_DIS_L0_POS           (0)
#define SCU_RCOSC_DIS_L0_MSK           (0x1ul << SCU_RCOSC_DIS_L0_POS)
#define SCU_AON_CLK_EN0_REG            SCU_AONCLKEN0
#define SCU_AON_CLK_EN0_POS            (0)
#define SCU_AON_CLK_EN0_MSK            (0xFFFFFFFFul << SCU_AON_CLK_EN0_POS)
#define SCU_AON_CLK_EN1_REG            SCU_AONCLKEN1
#define SCU_AON_CLK_EN1_POS            (0)
#define SCU_AON_CLK_EN1_MSK            (0x3FFFFul << SCU_AON_CLK_EN1_POS)
#define SCU_AON_I2C_CLK_SEL_REG        SCU_AONCLKMUXSEL
#define SCU_AON_I2C_CLK_SEL_POS        (0)
#define SCU_AON_I2C_CLK_SEL_MSK        (0x1ul << SCU_AON_I2C_CLK_SEL_POS)
#define SCU_PINMUX_X_AON_I2C1_SDA_REG  SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_I2C1_SDA_POS  (28)
#define SCU_PINMUX_X_AON_I2C1_SDA_MSK  (0x3ul << SCU_PINMUX_X_AON_I2C1_SDA_POS)
#define SCU_PINMUX_X_AON_I2C1_SCL_REG  SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_I2C1_SCL_POS  (26)
#define SCU_PINMUX_X_AON_I2C1_SCL_MSK  (0x3ul << SCU_PINMUX_X_AON_I2C1_SCL_POS)
#define SCU_PINMUX_X_AON_I2C0_SDA_PMIC_REG SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_I2C0_SDA_PMIC_POS (24)
#define SCU_PINMUX_X_AON_I2C0_SDA_PMIC_MSK (0x3ul << SCU_PINMUX_X_AON_I2C0_SDA_PMIC_POS)
#define SCU_PINMUX_X_AON_I2C0_SCL_PMIC_REG SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_I2C0_SCL_PMIC_POS (22)
#define SCU_PINMUX_X_AON_I2C0_SCL_PMIC_MSK (0x3ul << SCU_PINMUX_X_AON_I2C0_SCL_PMIC_POS)
#define SCU_PINMUX_X_PMIC_CTRL_REG     SCU_AONPINMUX0
#define SCU_PINMUX_X_PMIC_CTRL_POS     (20)
#define SCU_PINMUX_X_PMIC_CTRL_MSK     (0x3ul << SCU_PINMUX_X_PMIC_CTRL_POS)
#define SCU_PINMUX_X_AON_GPIO_REG      SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_GPIO_POS      (18)
#define SCU_PINMUX_X_AON_GPIO_MSK      (0x3ul << SCU_PINMUX_X_AON_GPIO_POS)
#define SCU_PINMUX_X_AON_SPI1_CSB0_REG SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_SPI1_CSB0_POS (16)
#define SCU_PINMUX_X_AON_SPI1_CSB0_MSK (0x3ul << SCU_PINMUX_X_AON_SPI1_CSB0_POS)
#define SCU_PINMUX_X_AON_SPI1_SDO_REG  SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_SPI1_SDO_POS  (14)
#define SCU_PINMUX_X_AON_SPI1_SDO_MSK  (0x3ul << SCU_PINMUX_X_AON_SPI1_SDO_POS)
#define SCU_PINMUX_X_AON_SPI1_SDI_REG  SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_SPI1_SDI_POS  (12)
#define SCU_PINMUX_X_AON_SPI1_SDI_MSK  (0x3ul << SCU_PINMUX_X_AON_SPI1_SDI_POS)
#define SCU_PINMUX_X_AON_SPI1_SCK_REG  SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_SPI1_SCK_POS  (10)
#define SCU_PINMUX_X_AON_SPI1_SCK_MSK  (0x3ul << SCU_PINMUX_X_AON_SPI1_SCK_POS)
#define SCU_PINMUX_X_AON_SPI0_CSB0_REG SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_SPI0_CSB0_POS (8)
#define SCU_PINMUX_X_AON_SPI0_CSB0_MSK (0x3ul << SCU_PINMUX_X_AON_SPI0_CSB0_POS)
#define SCU_PINMUX_X_AON_SPI0_SDO_REG  SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_SPI0_SDO_POS  (6)
#define SCU_PINMUX_X_AON_SPI0_SDO_MSK  (0x3ul << SCU_PINMUX_X_AON_SPI0_SDO_POS)
#define SCU_PINMUX_X_AON_SPI0_SDI_REG  SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_SPI0_SDI_POS  (4)
#define SCU_PINMUX_X_AON_SPI0_SDI_MSK  (0x3ul << SCU_PINMUX_X_AON_SPI0_SDI_POS)
#define SCU_PINMUX_X_AON_SPI0_SCK_REG  SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_SPI0_SCK_POS  (2)
#define SCU_PINMUX_X_AON_SPI0_SCK_MSK  (0x3ul << SCU_PINMUX_X_AON_SPI0_SCK_POS)
#define SCU_PINMUX_X_AON_PWM_REG       SCU_AONPINMUX0
#define SCU_PINMUX_X_AON_PWM_POS       (0)
#define SCU_PINMUX_X_AON_PWM_MSK       (0x3ul << SCU_PINMUX_X_AON_PWM_POS)
#define SCU_PINMUX_X_AON_UART_CTS_REG  SCU_AONPINMUX1
#define SCU_PINMUX_X_AON_UART_CTS_POS  (10)
#define SCU_PINMUX_X_AON_UART_CTS_MSK  (0x3ul << SCU_PINMUX_X_AON_UART_CTS_POS)
#define SCU_PINMUX_X_AON_UART_RTS_REG  SCU_AONPINMUX1
#define SCU_PINMUX_X_AON_UART_RTS_POS  (8)
#define SCU_PINMUX_X_AON_UART_RTS_MSK  (0x3ul << SCU_PINMUX_X_AON_UART_RTS_POS)
#define SCU_PINMUX_X_AON_UART_RXD_REG  SCU_AONPINMUX1
#define SCU_PINMUX_X_AON_UART_RXD_POS  (6)
#define SCU_PINMUX_X_AON_UART_RXD_MSK  (0x3ul << SCU_PINMUX_X_AON_UART_RXD_POS)
#define SCU_PINMUX_X_AON_UART_TXD_REG  SCU_AONPINMUX1
#define SCU_PINMUX_X_AON_UART_TXD_POS  (4)
#define SCU_PINMUX_X_AON_UART_TXD_MSK  (0x3ul << SCU_PINMUX_X_AON_UART_TXD_POS)
#define SCU_PINMUX_X_AON_I2C2_SDA_REG  SCU_AONPINMUX1
#define SCU_PINMUX_X_AON_I2C2_SDA_POS  (2)
#define SCU_PINMUX_X_AON_I2C2_SDA_MSK  (0x3ul << SCU_PINMUX_X_AON_I2C2_SDA_POS)
#define SCU_PINMUX_X_AON_I2C2_SCL_REG  SCU_AONPINMUX1
#define SCU_PINMUX_X_AON_I2C2_SCL_POS  (0)
#define SCU_PINMUX_X_AON_I2C2_SCL_MSK  (0x3ul << SCU_PINMUX_X_AON_I2C2_SCL_POS)
#define SCU_PADDRV_X_AON_SPI1_SDO_REG  SCU_AONPADDRV0
#define SCU_PADDRV_X_AON_SPI1_SDO_POS  (28)
#define SCU_PADDRV_X_AON_SPI1_SDO_MSK  (0xFul << SCU_PADDRV_X_AON_SPI1_SDO_POS)
#define SCU_PADDRV_X_AON_SPI1_SDI_REG  SCU_AONPADDRV0
#define SCU_PADDRV_X_AON_SPI1_SDI_POS  (24)
#define SCU_PADDRV_X_AON_SPI1_SDI_MSK  (0xFul << SCU_PADDRV_X_AON_SPI1_SDI_POS)
#define SCU_PADDRV_X_AON_SPI1_SCK_REG  SCU_AONPADDRV0
#define SCU_PADDRV_X_AON_SPI1_SCK_POS  (20)
#define SCU_PADDRV_X_AON_SPI1_SCK_MSK  (0xFul << SCU_PADDRV_X_AON_SPI1_SCK_POS)
#define SCU_PADDRV_X_AON_SPI0_CSB0_REG SCU_AONPADDRV0
#define SCU_PADDRV_X_AON_SPI0_CSB0_POS (16)
#define SCU_PADDRV_X_AON_SPI0_CSB0_MSK (0xFul << SCU_PADDRV_X_AON_SPI0_CSB0_POS)
#define SCU_PADDRV_X_AON_SPI0_SDO_REG  SCU_AONPADDRV0
#define SCU_PADDRV_X_AON_SPI0_SDO_POS  (12)
#define SCU_PADDRV_X_AON_SPI0_SDO_MSK  (0xFul << SCU_PADDRV_X_AON_SPI0_SDO_POS)
#define SCU_PADDRV_X_AON_SPI0_SDI_REG  SCU_AONPADDRV0
#define SCU_PADDRV_X_AON_SPI0_SDI_POS  (8)
#define SCU_PADDRV_X_AON_SPI0_SDI_MSK  (0xFul << SCU_PADDRV_X_AON_SPI0_SDI_POS)
#define SCU_PADDRV_X_AON_SPI0_SCK_REG  SCU_AONPADDRV0
#define SCU_PADDRV_X_AON_SPI0_SCK_POS  (4)
#define SCU_PADDRV_X_AON_SPI0_SCK_MSK  (0xFul << SCU_PADDRV_X_AON_SPI0_SCK_POS)
#define SCU_PADDRV_X_AON_PWM_REG       SCU_AONPADDRV0
#define SCU_PADDRV_X_AON_PWM_POS       (0)
#define SCU_PADDRV_X_AON_PWM_MSK       (0xFul << SCU_PADDRV_X_AON_PWM_POS)
#define SCU_PADDRV_X_AON_I2C1_SDA_REG  SCU_AONPADDRV1
#define SCU_PADDRV_X_AON_I2C1_SDA_POS  (24)
#define SCU_PADDRV_X_AON_I2C1_SDA_MSK  (0xFul << SCU_PADDRV_X_AON_I2C1_SDA_POS)
#define SCU_PADDRV_X_AON_I2C1_SCL_REG  SCU_AONPADDRV1
#define SCU_PADDRV_X_AON_I2C1_SCL_POS  (20)
#define SCU_PADDRV_X_AON_I2C1_SCL_MSK  (0xFul << SCU_PADDRV_X_AON_I2C1_SCL_POS)
#define SCU_PADDRV_X_AON_I2C0_SDA_PMIC_REG SCU_AONPADDRV1
#define SCU_PADDRV_X_AON_I2C0_SDA_PMIC_POS (16)
#define SCU_PADDRV_X_AON_I2C0_SDA_PMIC_MSK (0xFul << SCU_PADDRV_X_AON_I2C0_SDA_PMIC_POS)
#define SCU_PADDRV_X_AON_I2C0_SCL_PMIC_REG SCU_AONPADDRV1
#define SCU_PADDRV_X_AON_I2C0_SCL_PMIC_POS (12)
#define SCU_PADDRV_X_AON_I2C0_SCL_PMIC_MSK (0xFul << SCU_PADDRV_X_AON_I2C0_SCL_PMIC_POS)
#define SCU_PADDRV_X_PMIC_CTRL_REG     SCU_AONPADDRV1
#define SCU_PADDRV_X_PMIC_CTRL_POS     (8)
#define SCU_PADDRV_X_PMIC_CTRL_MSK     (0xFul << SCU_PADDRV_X_PMIC_CTRL_POS)
#define SCU_PADDRV_X_AON_GPIO_REG      SCU_AONPADDRV1
#define SCU_PADDRV_X_AON_GPIO_POS      (4)
#define SCU_PADDRV_X_AON_GPIO_MSK      (0xFul << SCU_PADDRV_X_AON_GPIO_POS)
#define SCU_PADDRV_X_AON_SPI1_CSB0_REG SCU_AONPADDRV1
#define SCU_PADDRV_X_AON_SPI1_CSB0_POS (0)
#define SCU_PADDRV_X_AON_SPI1_CSB0_MSK (0xFul << SCU_PADDRV_X_AON_SPI1_CSB0_POS)
#define SCU_PADDRV_X_AON_UART_CTS_REG  SCU_AONPADDRV2
#define SCU_PADDRV_X_AON_UART_CTS_POS  (20)
#define SCU_PADDRV_X_AON_UART_CTS_MSK  (0xFul << SCU_PADDRV_X_AON_UART_CTS_POS)
#define SCU_PADDRV_X_AON_UART_RTS_REG  SCU_AONPADDRV2
#define SCU_PADDRV_X_AON_UART_RTS_POS  (16)
#define SCU_PADDRV_X_AON_UART_RTS_MSK  (0xFul << SCU_PADDRV_X_AON_UART_RTS_POS)
#define SCU_PADDRV_X_AON_UART_RXD_REG  SCU_AONPADDRV2
#define SCU_PADDRV_X_AON_UART_RXD_POS  (12)
#define SCU_PADDRV_X_AON_UART_RXD_MSK  (0xFul << SCU_PADDRV_X_AON_UART_RXD_POS)
#define SCU_PADDRV_X_AON_UART_TXD_REG  SCU_AONPADDRV2
#define SCU_PADDRV_X_AON_UART_TXD_POS  (8)
#define SCU_PADDRV_X_AON_UART_TXD_MSK  (0xFul << SCU_PADDRV_X_AON_UART_TXD_POS)
#define SCU_PADDRV_X_AON_I2C2_SDA_REG  SCU_AONPADDRV2
#define SCU_PADDRV_X_AON_I2C2_SDA_POS  (4)
#define SCU_PADDRV_X_AON_I2C2_SDA_MSK  (0xFul << SCU_PADDRV_X_AON_I2C2_SDA_POS)
#define SCU_PADDRV_X_AON_I2C2_SCL_REG  SCU_AONPADDRV2
#define SCU_PADDRV_X_AON_I2C2_SCL_POS  (0)
#define SCU_PADDRV_X_AON_I2C2_SCL_MSK  (0xFul << SCU_PADDRV_X_AON_I2C2_SCL_POS)
#define SCU_PADCTRL_X_AON_SPI1_SDO_REG SCU_AONPADCTRL0
#define SCU_PADCTRL_X_AON_SPI1_SDO_POS (28)
#define SCU_PADCTRL_X_AON_SPI1_SDO_MSK (0xFul << SCU_PADCTRL_X_AON_SPI1_SDO_POS)
#define SCU_PADCTRL_X_AON_SPI1_SDI_REG SCU_AONPADCTRL0
#define SCU_PADCTRL_X_AON_SPI1_SDI_POS (24)
#define SCU_PADCTRL_X_AON_SPI1_SDI_MSK (0xFul << SCU_PADCTRL_X_AON_SPI1_SDI_POS)
#define SCU_PADCTRL_X_AON_SPI1_SCK_REG SCU_AONPADCTRL0
#define SCU_PADCTRL_X_AON_SPI1_SCK_POS (20)
#define SCU_PADCTRL_X_AON_SPI1_SCK_MSK (0xFul << SCU_PADCTRL_X_AON_SPI1_SCK_POS)
#define SCU_PADCTRL_X_AON_SPI0_CSB0_REG SCU_AONPADCTRL0
#define SCU_PADCTRL_X_AON_SPI0_CSB0_POS (16)
#define SCU_PADCTRL_X_AON_SPI0_CSB0_MSK (0xFul << SCU_PADCTRL_X_AON_SPI0_CSB0_POS)
#define SCU_PADCTRL_X_AON_SPI0_SDO_REG SCU_AONPADCTRL0
#define SCU_PADCTRL_X_AON_SPI0_SDO_POS (12)
#define SCU_PADCTRL_X_AON_SPI0_SDO_MSK (0xFul << SCU_PADCTRL_X_AON_SPI0_SDO_POS)
#define SCU_PADCTRL_X_AON_SPI0_SDI_REG SCU_AONPADCTRL0
#define SCU_PADCTRL_X_AON_SPI0_SDI_POS (8)
#define SCU_PADCTRL_X_AON_SPI0_SDI_MSK (0xFul << SCU_PADCTRL_X_AON_SPI0_SDI_POS)
#define SCU_PADCTRL_X_AON_SPI0_SCK_REG SCU_AONPADCTRL0
#define SCU_PADCTRL_X_AON_SPI0_SCK_POS (4)
#define SCU_PADCTRL_X_AON_SPI0_SCK_MSK (0xFul << SCU_PADCTRL_X_AON_SPI0_SCK_POS)
#define SCU_PADCTRL_X_AON_PWM_REG      SCU_AONPADCTRL0
#define SCU_PADCTRL_X_AON_PWM_POS      (0)
#define SCU_PADCTRL_X_AON_PWM_MSK      (0xFul << SCU_PADCTRL_X_AON_PWM_POS)
#define SCU_PADCTRL_X_AON_I2C1_SDA_REG SCU_AONPADCTRL1
#define SCU_PADCTRL_X_AON_I2C1_SDA_POS (24)
#define SCU_PADCTRL_X_AON_I2C1_SDA_MSK (0xFul << SCU_PADCTRL_X_AON_I2C1_SDA_POS)
#define SCU_PADCTRL_X_AON_I2C1_SCL_REG SCU_AONPADCTRL1
#define SCU_PADCTRL_X_AON_I2C1_SCL_POS (20)
#define SCU_PADCTRL_X_AON_I2C1_SCL_MSK (0xFul << SCU_PADCTRL_X_AON_I2C1_SCL_POS)
#define SCU_PADCTRL_X_AON_I2C0_SDA_PMIC_REG SCU_AONPADCTRL1
#define SCU_PADCTRL_X_AON_I2C0_SDA_PMIC_POS (16)
#define SCU_PADCTRL_X_AON_I2C0_SDA_PMIC_MSK (0xFul << SCU_PADCTRL_X_AON_I2C0_SDA_PMIC_POS)
#define SCU_PADCTRL_X_AON_I2C0_SCL_PMIC_REG SCU_AONPADCTRL1
#define SCU_PADCTRL_X_AON_I2C0_SCL_PMIC_POS (12)
#define SCU_PADCTRL_X_AON_I2C0_SCL_PMIC_MSK (0xFul << SCU_PADCTRL_X_AON_I2C0_SCL_PMIC_POS)
#define SCU_PADCTRL_X_PMIC_CTRL_REG    SCU_AONPADCTRL1
#define SCU_PADCTRL_X_PMIC_CTRL_POS    (8)
#define SCU_PADCTRL_X_PMIC_CTRL_MSK    (0xFul << SCU_PADCTRL_X_PMIC_CTRL_POS)
#define SCU_PADCTRL_X_AON_GPIO_REG     SCU_AONPADCTRL1
#define SCU_PADCTRL_X_AON_GPIO_POS     (4)
#define SCU_PADCTRL_X_AON_GPIO_MSK     (0xFul << SCU_PADCTRL_X_AON_GPIO_POS)
#define SCU_PADCTRL_X_AON_SPI1_CSB0_REG SCU_AONPADCTRL1
#define SCU_PADCTRL_X_AON_SPI1_CSB0_POS (0)
#define SCU_PADCTRL_X_AON_SPI1_CSB0_MSK (0xFul << SCU_PADCTRL_X_AON_SPI1_CSB0_POS)
#define SCU_PADCTRL_X_AON_UART_CTS_REG SCU_AONPADCTRL2
#define SCU_PADCTRL_X_AON_UART_CTS_POS (20)
#define SCU_PADCTRL_X_AON_UART_CTS_MSK (0xFul << SCU_PADCTRL_X_AON_UART_CTS_POS)
#define SCU_PADCTRL_X_AON_UART_RTS_REG SCU_AONPADCTRL2
#define SCU_PADCTRL_X_AON_UART_RTS_POS (16)
#define SCU_PADCTRL_X_AON_UART_RTS_MSK (0xFul << SCU_PADCTRL_X_AON_UART_RTS_POS)
#define SCU_PADCTRL_X_AON_UART_RXD_REG SCU_AONPADCTRL2
#define SCU_PADCTRL_X_AON_UART_RXD_POS (12)
#define SCU_PADCTRL_X_AON_UART_RXD_MSK (0xFul << SCU_PADCTRL_X_AON_UART_RXD_POS)
#define SCU_PADCTRL_X_AON_UART_TXD_REG SCU_AONPADCTRL2
#define SCU_PADCTRL_X_AON_UART_TXD_POS (8)
#define SCU_PADCTRL_X_AON_UART_TXD_MSK (0xFul << SCU_PADCTRL_X_AON_UART_TXD_POS)
#define SCU_PADCTRL_X_AON_I2C2_SDA_REG SCU_AONPADCTRL2
#define SCU_PADCTRL_X_AON_I2C2_SDA_POS (4)
#define SCU_PADCTRL_X_AON_I2C2_SDA_MSK (0xFul << SCU_PADCTRL_X_AON_I2C2_SDA_POS)
#define SCU_PADCTRL_X_AON_I2C2_SCL_REG SCU_AONPADCTRL2
#define SCU_PADCTRL_X_AON_I2C2_SCL_POS (0)
#define SCU_PADCTRL_X_AON_I2C2_SCL_MSK (0xFul << SCU_PADCTRL_X_AON_I2C2_SCL_POS)
#define SCU_AON_MAILBOX0_REG           SCU_AONMB0
#define SCU_AON_MAILBOX0_POS           (0)
#define SCU_AON_MAILBOX0_MSK           (0xFFFFFFFFul << SCU_AON_MAILBOX0_POS)
#define SCU_AON_MAILBOX1_REG           SCU_AONMB1
#define SCU_AON_MAILBOX1_POS           (0)
#define SCU_AON_MAILBOX1_MSK           (0xFFFFFFFFul << SCU_AON_MAILBOX1_POS)
#define SCU_AON_MAILBOX2_REG           SCU_AONMB2
#define SCU_AON_MAILBOX2_POS           (0)
#define SCU_AON_MAILBOX2_MSK           (0xFFFFFFFFul << SCU_AON_MAILBOX2_POS)
#define SCU_AON_MAILBOX3_REG           SCU_AONMB3
#define SCU_AON_MAILBOX3_POS           (0)
#define SCU_AON_MAILBOX3_MSK           (0xFFFFFFFFul << SCU_AON_MAILBOX3_POS)
#define SCU_SW_TO_E34_INT_STAT_REG     SCU_SYSIS
#define SCU_SW_TO_E34_INT_STAT_POS     (1)
#define SCU_SW_TO_E34_INT_STAT_MSK     (0x1ul << SCU_SW_TO_E34_INT_STAT_POS)
#define SCU_RESUME_CLK_INT_STAT_REG    SCU_SYSIS
#define SCU_RESUME_CLK_INT_STAT_POS    (0)
#define SCU_RESUME_CLK_INT_STAT_MSK    (0x1ul << SCU_RESUME_CLK_INT_STAT_POS)
#define SCU_SW_TO_E34_INT_STATR_REG    SCU_SYSRIS
#define SCU_SW_TO_E34_INT_STATR_POS    (1)
#define SCU_SW_TO_E34_INT_STATR_MSK    (0x1ul << SCU_SW_TO_E34_INT_STATR_POS)
#define SCU_RESUME_CLK_INT_STATR_REG   SCU_SYSRIS
#define SCU_RESUME_CLK_INT_STATR_POS   (0)
#define SCU_RESUME_CLK_INT_STATR_MSK   (0x1ul << SCU_RESUME_CLK_INT_STATR_POS)
#define SCU_SW_TO_E34_INT_EN_REG       SCU_SYSIE
#define SCU_SW_TO_E34_INT_EN_POS       (1)
#define SCU_SW_TO_E34_INT_EN_MSK       (0x1ul << SCU_SW_TO_E34_INT_EN_POS)
#define SCU_RESUME_CLK_INT_EN_REG      SCU_SYSIE
#define SCU_RESUME_CLK_INT_EN_POS      (0)
#define SCU_RESUME_CLK_INT_EN_MSK      (0x1ul << SCU_RESUME_CLK_INT_EN_POS)
#define SCU_SW_RESET_REG               SCU_SYSCTRL
#define SCU_SW_RESET_POS               (3)
#define SCU_SW_RESET_MSK               (0x1ul << SCU_SW_RESET_POS)
#define SCU_ENTER_SLEEP_REG            SCU_SYSCTRL
#define SCU_ENTER_SLEEP_POS            (2)
#define SCU_ENTER_SLEEP_MSK            (0x1ul << SCU_ENTER_SLEEP_POS)
#define SCU_ENTER_RTCM_REG             SCU_SYSCTRL
#define SCU_ENTER_RTCM_POS             (1)
#define SCU_ENTER_RTCM_MSK             (0x1ul << SCU_ENTER_RTCM_POS)
#define SCU_ENTER_STOP_CLOCK_REG       SCU_SYSCTRL
#define SCU_ENTER_STOP_CLOCK_POS       (0)
#define SCU_ENTER_STOP_CLOCK_MSK       (0x1ul << SCU_ENTER_STOP_CLOCK_POS)
#define SCU_ICACHE_VALIDBIT_RESET_EN_REG SCU_RETSRAMCTRL0
#define SCU_ICACHE_VALIDBIT_RESET_EN_POS (1)
#define SCU_ICACHE_VALIDBIT_RESET_EN_MSK (0x1ul << SCU_ICACHE_VALIDBIT_RESET_EN_POS)
#define SCU_ICACHE_INVALIDATION_EN_REG SCU_ICACHE_VALIDBIT_RESET_EN_REG
#define SCU_ICACHE_INVALIDATION_EN_POS SCU_ICACHE_VALIDBIT_RESET_EN_POS
#define SCU_ICACHE_INVALIDATION_EN_MSK SCU_ICACHE_VALIDBIT_RESET_EN_MSK
#define SCU_L2SRAM_DOMAIN_PWR_REG      SCU_RETSRAMCTRL0
#define SCU_L2SRAM_DOMAIN_PWR_POS      (0)
#define SCU_L2SRAM_DOMAIN_PWR_MSK      (0x1ul << SCU_L2SRAM_DOMAIN_PWR_POS)
#define SCU_E21_DISABLE_DEBUG_REG      SCU_E21CTRL
#define SCU_E21_DISABLE_DEBUG_POS      (4)
#define SCU_E21_DISABLE_DEBUG_MSK      (0x1ul << SCU_E21_DISABLE_DEBUG_POS)
#define SCU_E21_ECC_2BIT_OBS_REG       SCU_E21CTRL
#define SCU_E21_ECC_2BIT_OBS_POS       (3)
#define SCU_E21_ECC_2BIT_OBS_MSK       (0x1ul << SCU_E21_ECC_2BIT_OBS_POS)
#define SCU_E21_WFI_OBS_REG            SCU_E21CTRL
#define SCU_E21_WFI_OBS_POS            (2)
#define SCU_E21_WFI_OBS_MSK            (0x1ul << SCU_E21_WFI_OBS_POS)
#define SCU_E21_CORE_EN_REG            SCU_E21CTRL
#define SCU_E21_CORE_EN_POS            (1)
#define SCU_E21_CORE_EN_MSK            (0x1ul << SCU_E21_CORE_EN_POS)
#define SCU_SW_TO_E21_INT_REG          SCU_E21CTRL
#define SCU_SW_TO_E21_INT_POS          (0)
#define SCU_SW_TO_E21_INT_MSK          (0x1ul << SCU_SW_TO_E21_INT_POS)
#define SCU_I2C6_HS_REG                SCU_MISCCTRL
#define SCU_I2C6_HS_POS                (10)
#define SCU_I2C6_HS_MSK                (0x1ul << SCU_I2C6_HS_POS)
#define SCU_I2C5_HS_REG                SCU_MISCCTRL
#define SCU_I2C5_HS_POS                (9)
#define SCU_I2C5_HS_MSK                (0x1ul << SCU_I2C5_HS_POS)
#define SCU_I2C4_HS_REG                SCU_MISCCTRL
#define SCU_I2C4_HS_POS                (8)
#define SCU_I2C4_HS_MSK                (0x1ul << SCU_I2C4_HS_POS)
#define SCU_I2C3_HS_REG                SCU_MISCCTRL
#define SCU_I2C3_HS_POS                (7)
#define SCU_I2C3_HS_MSK                (0x1ul << SCU_I2C3_HS_POS)
#define SCU_I2C2_HS_REG                SCU_MISCCTRL
#define SCU_I2C2_HS_POS                (6)
#define SCU_I2C2_HS_MSK                (0x1ul << SCU_I2C2_HS_POS)
#define SCU_I2C1_HS_REG                SCU_MISCCTRL
#define SCU_I2C1_HS_POS                (5)
#define SCU_I2C1_HS_MSK                (0x1ul << SCU_I2C1_HS_POS)
#define SCU_I2C0_HS_REG                SCU_MISCCTRL
#define SCU_I2C0_HS_POS                (4)
#define SCU_I2C0_HS_MSK                (0x1ul << SCU_I2C0_HS_POS)
#define SCU_XCPB_PPROT_REG             SCU_MISCCTRL
#define SCU_XCPB_PPROT_POS             (3)
#define SCU_XCPB_PPROT_MSK             (0x1ul << SCU_XCPB_PPROT_POS)
#define SCU_UDL1_2_CEN_REG             SCU_MISCCTRL
#define SCU_UDL1_2_CEN_POS             (2)
#define SCU_UDL1_2_CEN_MSK             (0x1ul << SCU_UDL1_2_CEN_POS)
#define SCU_E34_DISABLE_DEBUG_REG      SCU_MISCCTRL
#define SCU_E34_DISABLE_DEBUG_POS      (1)
#define SCU_E34_DISABLE_DEBUG_MSK      (0x1ul << SCU_E34_DISABLE_DEBUG_POS)
#define SCU_JTAG_CHAIN_REG             SCU_MISCCTRL
#define SCU_JTAG_CHAIN_POS             (0)
#define SCU_JTAG_CHAIN_MSK             (0x1ul << SCU_JTAG_CHAIN_POS)
#define SCU_E34_AONI2C_INT_STAT_REG    SCU_E34IS
#define SCU_E34_AONI2C_INT_STAT_POS    (20)
#define SCU_E34_AONI2C_INT_STAT_MSK    (0x1Ful << SCU_E34_AONI2C_INT_STAT_POS)
#define SCU_E34_AONSPI_INT_STAT_REG    SCU_E34IS
#define SCU_E34_AONSPI_INT_STAT_POS    (18)
#define SCU_E34_AONSPI_INT_STAT_MSK    (0x3ul << SCU_E34_AONSPI_INT_STAT_POS)
#define SCU_E34_ADC1_INT_STAT_REG      SCU_E34IS
#define SCU_E34_ADC1_INT_STAT_POS      (14)
#define SCU_E34_ADC1_INT_STAT_MSK      (0xFul << SCU_E34_ADC1_INT_STAT_POS)
#define SCU_E34_ADC0_INT_STAT_REG      SCU_E34IS
#define SCU_E34_ADC0_INT_STAT_POS      (8)
#define SCU_E34_ADC0_INT_STAT_MSK      (0x3Ful << SCU_E34_ADC0_INT_STAT_POS)
#define SCU_E34_AONTMR_INT_STAT_REG    SCU_E34IS
#define SCU_E34_AONTMR_INT_STAT_POS    (4)
#define SCU_E34_AONTMR_INT_STAT_MSK    (0xFul << SCU_E34_AONTMR_INT_STAT_POS)
#define SCU_E34_FWTMR_INT_STAT_REG     SCU_E34IS
#define SCU_E34_FWTMR_INT_STAT_POS     (0)
#define SCU_E34_FWTMR_INT_STAT_MSK     (0xFul << SCU_E34_FWTMR_INT_STAT_POS)
#define SCU_E34_GLOBAL_INT_EN_REG      SCU_E34IE
#define SCU_E34_GLOBAL_INT_EN_POS      (27)
#define SCU_E34_GLOBAL_INT_EN_MSK      (0x1ul << SCU_E34_GLOBAL_INT_EN_POS)
#define SCU_E34_LOCAL_INT_EN_REG       SCU_E34IE
#define SCU_E34_LOCAL_INT_EN_POS       (26)
#define SCU_E34_LOCAL_INT_EN_MSK       (0x1ul << SCU_E34_LOCAL_INT_EN_POS)
#define SCU_E34_AONI2C_INT_EN_REG      SCU_E34IE
#define SCU_E34_AONI2C_INT_EN_POS      (20)
#define SCU_E34_AONI2C_INT_EN_MSK      (0x1Ful << SCU_E34_AONI2C_INT_EN_POS)
#define SCU_E34_AONSPI_INT_EN_REG      SCU_E34IE
#define SCU_E34_AONSPI_INT_EN_POS      (18)
#define SCU_E34_AONSPI_INT_EN_MSK      (0x3ul << SCU_E34_AONSPI_INT_EN_POS)
#define SCU_E34_ADC1_INT_EN_REG        SCU_E34IE
#define SCU_E34_ADC1_INT_EN_POS        (14)
#define SCU_E34_ADC1_INT_EN_MSK        (0xFul << SCU_E34_ADC1_INT_EN_POS)
#define SCU_E34_ADC0_INT_EN_REG        SCU_E34IE
#define SCU_E34_ADC0_INT_EN_POS        (8)
#define SCU_E34_ADC0_INT_EN_MSK        (0x3Ful << SCU_E34_ADC0_INT_EN_POS)
#define SCU_E34_AONTMR_INT_EN_REG      SCU_E34IE
#define SCU_E34_AONTMR_INT_EN_POS      (4)
#define SCU_E34_AONTMR_INT_EN_MSK      (0xFul << SCU_E34_AONTMR_INT_EN_POS)
#define SCU_E34_FWTMR_INT_EN_REG       SCU_E34IE
#define SCU_E34_FWTMR_INT_EN_POS       (0)
#define SCU_E34_FWTMR_INT_EN_MSK       (0xFul << SCU_E34_FWTMR_INT_EN_POS)
#define SCU_E34_AON_GPIO_STAT_REG      SCU_E34GPIS
#define SCU_E34_AON_GPIO_STAT_POS      (8)
#define SCU_E34_AON_GPIO_STAT_MSK      (0x1FFFFFul << SCU_E34_AON_GPIO_STAT_POS)
#define SCU_E34_RTCM_GPIO_STAT_REG     SCU_E34GPIS
#define SCU_E34_RTCM_GPIO_STAT_POS     (0)
#define SCU_E34_RTCM_GPIO_STAT_MSK     (0xFul << SCU_E34_RTCM_GPIO_STAT_POS)
#define SCU_E34_AON_GPIO_EN_REG        SCU_E34GPIE
#define SCU_E34_AON_GPIO_EN_POS        (8)
#define SCU_E34_AON_GPIO_EN_MSK        (0x1FFFFFul << SCU_E34_AON_GPIO_EN_POS)
#define SCU_E34_RTCM_GPIO_EN_REG       SCU_E34GPIE
#define SCU_E34_RTCM_GPIO_EN_POS       (0)
#define SCU_E34_RTCM_GPIO_EN_MSK       (0xFul << SCU_E34_RTCM_GPIO_EN_POS)
#define SCU_SWRST_MSK0_REG             SCU_SWRSTMSK0
#define SCU_SWRST_MSK0_POS             (0)
#define SCU_SWRST_MSK0_MSK             (0xFFFFFFFFul << SCU_SWRST_MSK0_POS)
#define SCU_SWRST_MSK1_REG             SCU_SWRSTMSK1
#define SCU_SWRST_MSK1_POS             (0)
#define SCU_SWRST_MSK1_MSK             (0xFFFFFFFFul << SCU_SWRST_MSK1_POS)
#define SCU_SWRST_MSK2_REG             SCU_SWRSTMSK2
#define SCU_SWRST_MSK2_POS             (0)
#define SCU_SWRST_MSK2_MSK             (0xFFFFFFFFul << SCU_SWRST_MSK2_POS)
#define SCU_RESUME_EVNT_STATUS0_REG    SCU_RESCLKSTAT0
#define SCU_RESUME_EVNT_STATUS0_POS    (1)
#define SCU_RESUME_EVNT_STATUS0_MSK    (0x7FFFul << SCU_RESUME_EVNT_STATUS0_POS)
#define SCU_RSVD_STATUS0_REG           SCU_RESCLKSTAT0
#define SCU_RSVD_STATUS0_POS           (0)
#define SCU_RSVD_STATUS0_MSK           (0x1ul << SCU_RSVD_STATUS0_POS)
#define SCU_RESUME_EVNT_STATUS1_REG    SCU_RESCLKSTAT1
#define SCU_RESUME_EVNT_STATUS1_POS    (1)
#define SCU_RESUME_EVNT_STATUS1_MSK    (0x7FFFFFFFul << SCU_RESUME_EVNT_STATUS1_POS)
#define SCU_RSVD_STATUS1_REG           SCU_RESCLKSTAT1
#define SCU_RSVD_STATUS1_POS           (0)
#define SCU_RSVD_STATUS1_MSK           (0x1ul << SCU_RSVD_STATUS1_POS)
#define SCU_RESUME_EVNT_STATUS2_REG    SCU_RESCLKSTAT2
#define SCU_RESUME_EVNT_STATUS2_POS    (0)
#define SCU_RESUME_EVNT_STATUS2_MSK    (0xFFFFFFFFul << SCU_RESUME_EVNT_STATUS2_POS)
#define SCU_RESUME_EVNT_STATUS3_REG    SCU_RESCLKSTAT3
#define SCU_RESUME_EVNT_STATUS3_POS    (0)
#define SCU_RESUME_EVNT_STATUS3_MSK    (0xFFFFFFFFul << SCU_RESUME_EVNT_STATUS3_POS)
#define SCU_RESUME_EVNT_STATUS4_REG    SCU_RESCLKSTAT4
#define SCU_RESUME_EVNT_STATUS4_POS    (0)
#define SCU_RESUME_EVNT_STATUS4_MSK    (0xFFFFFFFFul << SCU_RESUME_EVNT_STATUS4_POS)
#define SCU_RESUME_EVNT_EN0_REG        SCU_RESCLKEN0
#define SCU_RESUME_EVNT_EN0_POS        (1)
#define SCU_RESUME_EVNT_EN0_MSK        (0x7FFFul << SCU_RESUME_EVNT_EN0_POS)
#define SCU_RSVD0_REG                  SCU_RESCLKEN0
#define SCU_RSVD0_POS                  (0)
#define SCU_RSVD0_MSK                  (0x1ul << SCU_RSVD0_POS)
#define SCU_RESUME_EVNT_EN1_REG        SCU_RESCLKEN1
#define SCU_RESUME_EVNT_EN1_POS        (1)
#define SCU_RESUME_EVNT_EN1_MSK        (0x7FFFFFFFul << SCU_RESUME_EVNT_EN1_POS)
#define SCU_RSVD1_REG                  SCU_RESCLKEN1
#define SCU_RSVD1_POS                  (0)
#define SCU_RSVD1_MSK                  (0x1ul << SCU_RSVD1_POS)
#define SCU_RESUME_EVNT_EN2_REG        SCU_RESCLKEN2
#define SCU_RESUME_EVNT_EN2_POS        (0)
#define SCU_RESUME_EVNT_EN2_MSK        (0xFFFFFFFFul << SCU_RESUME_EVNT_EN2_POS)
#define SCU_RESUME_EVNT_EN3_REG        SCU_RESCLKEN3
#define SCU_RESUME_EVNT_EN3_POS        (0)
#define SCU_RESUME_EVNT_EN3_MSK        (0xFFFFFFFFul << SCU_RESUME_EVNT_EN3_POS)
#define SCU_RESUME_EVNT_EN4_REG        SCU_RESCLKEN4
#define SCU_RESUME_EVNT_EN4_POS        (0)
#define SCU_RESUME_EVNT_EN4_MSK        (0xFFFFFFFFul << SCU_RESUME_EVNT_EN4_POS)
#define SCU_DMA1_ALT_SEL_REG           SCU_DMAALT
#define SCU_DMA1_ALT_SEL_POS           (6)
#define SCU_DMA1_ALT_SEL_MSK           (0xFFul << SCU_DMA1_ALT_SEL_POS)
#define SCU_DMA0_ALT_SEL_REG           SCU_DMAALT
#define SCU_DMA0_ALT_SEL_POS           (0)
#define SCU_DMA0_ALT_SEL_MSK           (0x3Ful << SCU_DMA0_ALT_SEL_POS)
#define SCU_SWRST_N0_REG               SCU_SWRSTN0
#define SCU_SWRST_N0_POS               (0)
#define SCU_SWRST_N0_MSK               (0x7FFFFFFul << SCU_SWRST_N0_POS)
#define SCU_SWRST_N1_REG               SCU_SWRSTN1
#define SCU_SWRST_N1_POS               (0)
#define SCU_SWRST_N1_MSK               (0xFFFFFFFFul << SCU_SWRST_N1_POS)
#define SCU_SWRST_N2_REG               SCU_SWRSTN2
#define SCU_SWRST_N2_POS               (0)
#define SCU_SWRST_N2_MSK               (0xFFFFul << SCU_SWRST_N2_POS)
#define SCU_GCRG4_CFG_PLLBYPASS_REG    SCU_GCRG
#define SCU_GCRG4_CFG_PLLBYPASS_POS    (3)
#define SCU_GCRG4_CFG_PLLBYPASS_MSK    (0x1ul << SCU_GCRG4_CFG_PLLBYPASS_POS)
#define SCU_GCRG3_CFG_PLLBYPASS_REG    SCU_GCRG
#define SCU_GCRG3_CFG_PLLBYPASS_POS    (2)
#define SCU_GCRG3_CFG_PLLBYPASS_MSK    (0x1ul << SCU_GCRG3_CFG_PLLBYPASS_POS)
#define SCU_GCRG2_CFG_PLLBYPASS_REG    SCU_GCRG
#define SCU_GCRG2_CFG_PLLBYPASS_POS    (1)
#define SCU_GCRG2_CFG_PLLBYPASS_MSK    (0x1ul << SCU_GCRG2_CFG_PLLBYPASS_POS)
#define SCU_GCRG1_CFG_PLLBYPASS_REG    SCU_GCRG
#define SCU_GCRG1_CFG_PLLBYPASS_POS    (0)
#define SCU_GCRG1_CFG_PLLBYPASS_MSK    (0x1ul << SCU_GCRG1_CFG_PLLBYPASS_POS)
#define SCU_HCLK_EN0_REG               SCU_HCLKEN0
#define SCU_HCLK_EN0_POS               (0)
#define SCU_HCLK_EN0_MSK               (0x7FFFFFFFul << SCU_HCLK_EN0_POS)
#define SCU_HCLK_EN1_REG               SCU_HCLKEN1
#define SCU_HCLK_EN1_POS               (0)
#define SCU_HCLK_EN1_MSK               (0x3FFul << SCU_HCLK_EN1_POS)
#define SCU_PCLK_EN_REG                SCU_PCLKEN
#define SCU_PCLK_EN_POS                (0)
#define SCU_PCLK_EN_MSK                (0x7FFFFFul << SCU_PCLK_EN_POS)
#define SCU_AXSC_HCLK_EN0_REG          SCU_AXSCHCLKEN0
#define SCU_AXSC_HCLK_EN0_POS          (0)
#define SCU_AXSC_HCLK_EN0_MSK          (0x7FFFFFFFul << SCU_AXSC_HCLK_EN0_POS)
#define SCU_AXSC_HCLK_EN1_REG          SCU_AXSCHCLKEN1
#define SCU_AXSC_HCLK_EN1_POS          (0)
#define SCU_AXSC_HCLK_EN1_MSK          (0x3FFul << SCU_AXSC_HCLK_EN1_POS)
#define SCU_AXSC_PCLK_EN_REG           SCU_AXSCPCLKEN
#define SCU_AXSC_PCLK_EN_POS           (0)
#define SCU_AXSC_PCLK_EN_MSK           (0x7FFFFFul << SCU_AXSC_PCLK_EN_POS)
#define SCU_CLK_EN0_REG                SCU_CLKEN0
#define SCU_CLK_EN0_POS                (0)
#define SCU_CLK_EN0_MSK                (0xFFFFFFFFul << SCU_CLK_EN0_POS)
#define SCU_CLK_EN1_REG                SCU_CLKEN1
#define SCU_CLK_EN1_POS                (0)
#define SCU_CLK_EN1_MSK                (0x1FFul << SCU_CLK_EN1_POS)
#define SCU_CLK_EN2_REG                SCU_CLKEN2
#define SCU_CLK_EN2_POS                (0)
#define SCU_CLK_EN2_MSK                (0x3Ful << SCU_CLK_EN2_POS)
#define SCU_NAON_PLL4_MIPI_CLK_SEL_REG SCU_CLKMUXSEL0
#define SCU_NAON_PLL4_MIPI_CLK_SEL_POS (5)
#define SCU_NAON_PLL4_MIPI_CLK_SEL_MSK (0x1ul << SCU_NAON_PLL4_MIPI_CLK_SEL_POS)
#define SCU_NAON_DC_CLK_SEL_REG        SCU_CLKMUXSEL0
#define SCU_NAON_DC_CLK_SEL_POS        (4)
#define SCU_NAON_DC_CLK_SEL_MSK        (0x1ul << SCU_NAON_DC_CLK_SEL_POS)
#define SCU_NAON_AUDIO_CLK_SEL_REG     SCU_CLKMUXSEL0
#define SCU_NAON_AUDIO_CLK_SEL_POS     (0)
#define SCU_NAON_AUDIO_CLK_SEL_MSK     (0xFul << SCU_NAON_AUDIO_CLK_SEL_POS)
#define SCU_NAON_DIV0_REG              SCU_CLKDIV
#define SCU_NAON_DIV0_POS              (0)
#define SCU_NAON_DIV0_MSK              (0x1FFFFFFul << SCU_NAON_DIV0_POS)
#define SCU_PINMUX_X_SDIO_CMD_REG      SCU_PINMUX0
#define SCU_PINMUX_X_SDIO_CMD_POS      (28)
#define SCU_PINMUX_X_SDIO_CMD_MSK      (0xFul << SCU_PINMUX_X_SDIO_CMD_POS)
#define SCU_PINMUX_X_SDIO_CLK_REG      SCU_PINMUX0
#define SCU_PINMUX_X_SDIO_CLK_POS      (24)
#define SCU_PINMUX_X_SDIO_CLK_MSK      (0xFul << SCU_PINMUX_X_SDIO_CLK_POS)
#define SCU_PINMUX_X_OSPI_DQS_REG      SCU_PINMUX0
#define SCU_PINMUX_X_OSPI_DQS_POS      (20)
#define SCU_PINMUX_X_OSPI_DQS_MSK      (0xFul << SCU_PINMUX_X_OSPI_DQS_POS)
#define SCU_PINMUX_X_OSPI_SD7_REG      SCU_PINMUX0
#define SCU_PINMUX_X_OSPI_SD7_POS      (16)
#define SCU_PINMUX_X_OSPI_SD7_MSK      (0xFul << SCU_PINMUX_X_OSPI_SD7_POS)
#define SCU_PINMUX_X_OSPI_SD6_REG      SCU_PINMUX0
#define SCU_PINMUX_X_OSPI_SD6_POS      (12)
#define SCU_PINMUX_X_OSPI_SD6_MSK      (0xFul << SCU_PINMUX_X_OSPI_SD6_POS)
#define SCU_PINMUX_X_OSPI_SD5_REG      SCU_PINMUX0
#define SCU_PINMUX_X_OSPI_SD5_POS      (8)
#define SCU_PINMUX_X_OSPI_SD5_MSK      (0xFul << SCU_PINMUX_X_OSPI_SD5_POS)
#define SCU_PINMUX_X_OSPI_SD4_REG      SCU_PINMUX0
#define SCU_PINMUX_X_OSPI_SD4_POS      (4)
#define SCU_PINMUX_X_OSPI_SD4_MSK      (0xFul << SCU_PINMUX_X_OSPI_SD4_POS)
#define SCU_PINMUX_X_OSPI_CSB1_REG     SCU_PINMUX0
#define SCU_PINMUX_X_OSPI_CSB1_POS     (0)
#define SCU_PINMUX_X_OSPI_CSB1_MSK     (0xFul << SCU_PINMUX_X_OSPI_CSB1_POS)
#define SCU_PINMUX_X_SDIO_DATA7_REG    SCU_PINMUX1
#define SCU_PINMUX_X_SDIO_DATA7_POS    (28)
#define SCU_PINMUX_X_SDIO_DATA7_MSK    (0xFul << SCU_PINMUX_X_SDIO_DATA7_POS)
#define SCU_PINMUX_X_SDIO_DATA6_REG    SCU_PINMUX1
#define SCU_PINMUX_X_SDIO_DATA6_POS    (24)
#define SCU_PINMUX_X_SDIO_DATA6_MSK    (0xFul << SCU_PINMUX_X_SDIO_DATA6_POS)
#define SCU_PINMUX_X_SDIO_DATA5_REG    SCU_PINMUX1
#define SCU_PINMUX_X_SDIO_DATA5_POS    (20)
#define SCU_PINMUX_X_SDIO_DATA5_MSK    (0xFul << SCU_PINMUX_X_SDIO_DATA5_POS)
#define SCU_PINMUX_X_SDIO_DATA4_REG    SCU_PINMUX1
#define SCU_PINMUX_X_SDIO_DATA4_POS    (16)
#define SCU_PINMUX_X_SDIO_DATA4_MSK    (0xFul << SCU_PINMUX_X_SDIO_DATA4_POS)
#define SCU_PINMUX_X_SDIO_DATA3_REG    SCU_PINMUX1
#define SCU_PINMUX_X_SDIO_DATA3_POS    (12)
#define SCU_PINMUX_X_SDIO_DATA3_MSK    (0xFul << SCU_PINMUX_X_SDIO_DATA3_POS)
#define SCU_PINMUX_X_SDIO_DATA2_REG    SCU_PINMUX1
#define SCU_PINMUX_X_SDIO_DATA2_POS    (8)
#define SCU_PINMUX_X_SDIO_DATA2_MSK    (0xFul << SCU_PINMUX_X_SDIO_DATA2_POS)
#define SCU_PINMUX_X_SDIO_DATA1_REG    SCU_PINMUX1
#define SCU_PINMUX_X_SDIO_DATA1_POS    (4)
#define SCU_PINMUX_X_SDIO_DATA1_MSK    (0xFul << SCU_PINMUX_X_SDIO_DATA1_POS)
#define SCU_PINMUX_X_SDIO_DATA0_REG    SCU_PINMUX1
#define SCU_PINMUX_X_SDIO_DATA0_POS    (0)
#define SCU_PINMUX_X_SDIO_DATA0_MSK    (0xFul << SCU_PINMUX_X_SDIO_DATA0_POS)
#define SCU_PINMUX_X_LCD_SPI_SD_REG    SCU_PINMUX2
#define SCU_PINMUX_X_LCD_SPI_SD_POS    (28)
#define SCU_PINMUX_X_LCD_SPI_SD_MSK    (0xFul << SCU_PINMUX_X_LCD_SPI_SD_POS)
#define SCU_PINMUX_X_LCD_SPI_SCK_REG   SCU_PINMUX2
#define SCU_PINMUX_X_LCD_SPI_SCK_POS   (24)
#define SCU_PINMUX_X_LCD_SPI_SCK_MSK   (0xFul << SCU_PINMUX_X_LCD_SPI_SCK_POS)
#define SCU_PINMUX_X_LCD_RESETB_REG    SCU_PINMUX2
#define SCU_PINMUX_X_LCD_RESETB_POS    (20)
#define SCU_PINMUX_X_LCD_RESETB_MSK    (0xFul << SCU_PINMUX_X_LCD_RESETB_POS)
#define SCU_PINMUX_X_JTAG_GPIO_SEL_REG SCU_PINMUX2
#define SCU_PINMUX_X_JTAG_GPIO_SEL_POS (16)
#define SCU_PINMUX_X_JTAG_GPIO_SEL_MSK (0xFul << SCU_PINMUX_X_JTAG_GPIO_SEL_POS)
#define SCU_PINMUX_X_CPU_TDO_REG       SCU_PINMUX2
#define SCU_PINMUX_X_CPU_TDO_POS       (12)
#define SCU_PINMUX_X_CPU_TDO_MSK       (0xFul << SCU_PINMUX_X_CPU_TDO_POS)
#define SCU_PINMUX_X_CPU_TDI_REG       SCU_PINMUX2
#define SCU_PINMUX_X_CPU_TDI_POS       (8)
#define SCU_PINMUX_X_CPU_TDI_MSK       (0xFul << SCU_PINMUX_X_CPU_TDI_POS)
#define SCU_PINMUX_X_CPU_TCK_REG       SCU_PINMUX2
#define SCU_PINMUX_X_CPU_TCK_POS       (4)
#define SCU_PINMUX_X_CPU_TCK_MSK       (0xFul << SCU_PINMUX_X_CPU_TCK_POS)
#define SCU_PINMUX_X_CPU_TMS_REG       SCU_PINMUX2
#define SCU_PINMUX_X_CPU_TMS_POS       (0)
#define SCU_PINMUX_X_CPU_TMS_MSK       (0xFul << SCU_PINMUX_X_CPU_TMS_POS)
#define SCU_PINMUX_X_I2C0_SDA_REG      SCU_PINMUX3
#define SCU_PINMUX_X_I2C0_SDA_POS      (28)
#define SCU_PINMUX_X_I2C0_SDA_MSK      (0xFul << SCU_PINMUX_X_I2C0_SDA_POS)
#define SCU_PINMUX_X_I2C0_SCL_REG      SCU_PINMUX3
#define SCU_PINMUX_X_I2C0_SCL_POS      (24)
#define SCU_PINMUX_X_I2C0_SCL_MSK      (0xFul << SCU_PINMUX_X_I2C0_SCL_POS)
#define SCU_PINMUX_X_UART0_CTS_ISP_REG SCU_PINMUX3
#define SCU_PINMUX_X_UART0_CTS_ISP_POS (20)
#define SCU_PINMUX_X_UART0_CTS_ISP_MSK (0xFul << SCU_PINMUX_X_UART0_CTS_ISP_POS)
#define SCU_PINMUX_X_UART0_RTS_ISP_REG SCU_PINMUX3
#define SCU_PINMUX_X_UART0_RTS_ISP_POS (16)
#define SCU_PINMUX_X_UART0_RTS_ISP_MSK (0xFul << SCU_PINMUX_X_UART0_RTS_ISP_POS)
#define SCU_PINMUX_X_UART0_RXD_ISP_REG SCU_PINMUX3
#define SCU_PINMUX_X_UART0_RXD_ISP_POS (12)
#define SCU_PINMUX_X_UART0_RXD_ISP_MSK (0xFul << SCU_PINMUX_X_UART0_RXD_ISP_POS)
#define SCU_PINMUX_X_UART0_TXD_ISP_REG SCU_PINMUX3
#define SCU_PINMUX_X_UART0_TXD_ISP_POS (8)
#define SCU_PINMUX_X_UART0_TXD_ISP_MSK (0xFul << SCU_PINMUX_X_UART0_TXD_ISP_POS)
#define SCU_PINMUX_X_LCD_SPI_DCX_REG   SCU_PINMUX3
#define SCU_PINMUX_X_LCD_SPI_DCX_POS   (4)
#define SCU_PINMUX_X_LCD_SPI_DCX_MSK   (0xFul << SCU_PINMUX_X_LCD_SPI_DCX_POS)
#define SCU_PINMUX_X_LCD_SPI_CSB_REG   SCU_PINMUX3
#define SCU_PINMUX_X_LCD_SPI_CSB_POS   (0)
#define SCU_PINMUX_X_LCD_SPI_CSB_MSK   (0xFul << SCU_PINMUX_X_LCD_SPI_CSB_POS)
#define SCU_PINMUX_X_SPI0_CSB0_REG     SCU_PINMUX4
#define SCU_PINMUX_X_SPI0_CSB0_POS     (28)
#define SCU_PINMUX_X_SPI0_CSB0_MSK     (0xFul << SCU_PINMUX_X_SPI0_CSB0_POS)
#define SCU_PINMUX_X_SPI0_SDO_REG      SCU_PINMUX4
#define SCU_PINMUX_X_SPI0_SDO_POS      (24)
#define SCU_PINMUX_X_SPI0_SDO_MSK      (0xFul << SCU_PINMUX_X_SPI0_SDO_POS)
#define SCU_PINMUX_X_SPI0_SDI_REG      SCU_PINMUX4
#define SCU_PINMUX_X_SPI0_SDI_POS      (20)
#define SCU_PINMUX_X_SPI0_SDI_MSK      (0xFul << SCU_PINMUX_X_SPI0_SDI_POS)
#define SCU_PINMUX_X_SPI0_SCK_REG      SCU_PINMUX4
#define SCU_PINMUX_X_SPI0_SCK_POS      (16)
#define SCU_PINMUX_X_SPI0_SCK_MSK      (0xFul << SCU_PINMUX_X_SPI0_SCK_POS)
#define SCU_PINMUX_X_UART1_CTS_REG     SCU_PINMUX4
#define SCU_PINMUX_X_UART1_CTS_POS     (12)
#define SCU_PINMUX_X_UART1_CTS_MSK     (0xFul << SCU_PINMUX_X_UART1_CTS_POS)
#define SCU_PINMUX_X_UART1_RTS_REG     SCU_PINMUX4
#define SCU_PINMUX_X_UART1_RTS_POS     (8)
#define SCU_PINMUX_X_UART1_RTS_MSK     (0xFul << SCU_PINMUX_X_UART1_RTS_POS)
#define SCU_PINMUX_X_UART1_RXD_REG     SCU_PINMUX4
#define SCU_PINMUX_X_UART1_RXD_POS     (4)
#define SCU_PINMUX_X_UART1_RXD_MSK     (0xFul << SCU_PINMUX_X_UART1_RXD_POS)
#define SCU_PINMUX_X_UART1_TXD_REG     SCU_PINMUX4
#define SCU_PINMUX_X_UART1_TXD_POS     (0)
#define SCU_PINMUX_X_UART1_TXD_MSK     (0xFul << SCU_PINMUX_X_UART1_TXD_POS)
#define SCU_PINMUX_X_I2S0_BCLK_REG     SCU_PINMUX5
#define SCU_PINMUX_X_I2S0_BCLK_POS     (24)
#define SCU_PINMUX_X_I2S0_BCLK_MSK     (0xFul << SCU_PINMUX_X_I2S0_BCLK_POS)
#define SCU_PINMUX_X_I2S0_WS_REG       SCU_PINMUX5
#define SCU_PINMUX_X_I2S0_WS_POS       (20)
#define SCU_PINMUX_X_I2S0_WS_MSK       (0xFul << SCU_PINMUX_X_I2S0_WS_POS)
#define SCU_PINMUX_X_SPI1_CSB0_REG     SCU_PINMUX5
#define SCU_PINMUX_X_SPI1_CSB0_POS     (16)
#define SCU_PINMUX_X_SPI1_CSB0_MSK     (0xFul << SCU_PINMUX_X_SPI1_CSB0_POS)
#define SCU_PINMUX_X_SPI1_SDO_REG      SCU_PINMUX5
#define SCU_PINMUX_X_SPI1_SDO_POS      (12)
#define SCU_PINMUX_X_SPI1_SDO_MSK      (0xFul << SCU_PINMUX_X_SPI1_SDO_POS)
#define SCU_PINMUX_X_SPI1_SDI_REG      SCU_PINMUX5
#define SCU_PINMUX_X_SPI1_SDI_POS      (8)
#define SCU_PINMUX_X_SPI1_SDI_MSK      (0xFul << SCU_PINMUX_X_SPI1_SDI_POS)
#define SCU_PINMUX_X_SPI1_SCK_REG      SCU_PINMUX5
#define SCU_PINMUX_X_SPI1_SCK_POS      (4)
#define SCU_PINMUX_X_SPI1_SCK_MSK      (0xFul << SCU_PINMUX_X_SPI1_SCK_POS)
#define SCU_PINMUX_X_SPI0_CSB1_REG     SCU_PINMUX5
#define SCU_PINMUX_X_SPI0_CSB1_POS     (0)
#define SCU_PINMUX_X_SPI0_CSB1_MSK     (0xFul << SCU_PINMUX_X_SPI0_CSB1_POS)
#define SCU_PINMUX_X_LED_PWM1_REG      SCU_PINMUX6
#define SCU_PINMUX_X_LED_PWM1_POS      (28)
#define SCU_PINMUX_X_LED_PWM1_MSK      (0xFul << SCU_PINMUX_X_LED_PWM1_POS)
#define SCU_PINMUX_X_LED_PWM0_REG      SCU_PINMUX6
#define SCU_PINMUX_X_LED_PWM0_POS      (24)
#define SCU_PINMUX_X_LED_PWM0_MSK      (0xFul << SCU_PINMUX_X_LED_PWM0_POS)
#define SCU_PINMUX_X_I2S1_SOUT_REG     SCU_PINMUX6
#define SCU_PINMUX_X_I2S1_SOUT_POS     (20)
#define SCU_PINMUX_X_I2S1_SOUT_MSK     (0xFul << SCU_PINMUX_X_I2S1_SOUT_POS)
#define SCU_PINMUX_X_I2S1_SIN_REG      SCU_PINMUX6
#define SCU_PINMUX_X_I2S1_SIN_POS      (16)
#define SCU_PINMUX_X_I2S1_SIN_MSK      (0xFul << SCU_PINMUX_X_I2S1_SIN_POS)
#define SCU_PINMUX_X_I2S1_BCLK_REG     SCU_PINMUX6
#define SCU_PINMUX_X_I2S1_BCLK_POS     (12)
#define SCU_PINMUX_X_I2S1_BCLK_MSK     (0xFul << SCU_PINMUX_X_I2S1_BCLK_POS)
#define SCU_PINMUX_X_I2S1_WS_REG       SCU_PINMUX6
#define SCU_PINMUX_X_I2S1_WS_POS       (8)
#define SCU_PINMUX_X_I2S1_WS_MSK       (0xFul << SCU_PINMUX_X_I2S1_WS_POS)
#define SCU_PINMUX_X_I2S0_MCLK_REG     SCU_PINMUX6
#define SCU_PINMUX_X_I2S0_MCLK_POS     (4)
#define SCU_PINMUX_X_I2S0_MCLK_MSK     (0xFul << SCU_PINMUX_X_I2S0_MCLK_POS)
#define SCU_PINMUX_X_I2S0_SD_REG       SCU_PINMUX6
#define SCU_PINMUX_X_I2S0_SD_POS       (0)
#define SCU_PINMUX_X_I2S0_SD_MSK       (0xFul << SCU_PINMUX_X_I2S0_SD_POS)
#define SCU_PINMUX_X_SPI2_CSB0_REG     SCU_PINMUX7
#define SCU_PINMUX_X_SPI2_CSB0_POS     (28)
#define SCU_PINMUX_X_SPI2_CSB0_MSK     (0xFul << SCU_PINMUX_X_SPI2_CSB0_POS)
#define SCU_PINMUX_X_SPI2_SDO_REG      SCU_PINMUX7
#define SCU_PINMUX_X_SPI2_SDO_POS      (24)
#define SCU_PINMUX_X_SPI2_SDO_MSK      (0xFul << SCU_PINMUX_X_SPI2_SDO_POS)
#define SCU_PINMUX_X_SPI2_SDI_REG      SCU_PINMUX7
#define SCU_PINMUX_X_SPI2_SDI_POS      (20)
#define SCU_PINMUX_X_SPI2_SDI_MSK      (0xFul << SCU_PINMUX_X_SPI2_SDI_POS)
#define SCU_PINMUX_X_SPI2_SCK_REG      SCU_PINMUX7
#define SCU_PINMUX_X_SPI2_SCK_POS      (16)
#define SCU_PINMUX_X_SPI2_SCK_MSK      (0xFul << SCU_PINMUX_X_SPI2_SCK_POS)
#define SCU_PINMUX_X_PDM0_DIN_REG      SCU_PINMUX7
#define SCU_PINMUX_X_PDM0_DIN_POS      (12)
#define SCU_PINMUX_X_PDM0_DIN_MSK      (0xFul << SCU_PINMUX_X_PDM0_DIN_POS)
#define SCU_PINMUX_X_PDM0_CLK_REG      SCU_PINMUX7
#define SCU_PINMUX_X_PDM0_CLK_POS      (8)
#define SCU_PINMUX_X_PDM0_CLK_MSK      (0xFul << SCU_PINMUX_X_PDM0_CLK_POS)
#define SCU_PINMUX_X_LED_PWM3_REG      SCU_PINMUX7
#define SCU_PINMUX_X_LED_PWM3_POS      (4)
#define SCU_PINMUX_X_LED_PWM3_MSK      (0xFul << SCU_PINMUX_X_LED_PWM3_POS)
#define SCU_PINMUX_X_LED_PWM2_REG      SCU_PINMUX7
#define SCU_PINMUX_X_LED_PWM2_POS      (0)
#define SCU_PINMUX_X_LED_PWM2_MSK      (0xFul << SCU_PINMUX_X_LED_PWM2_POS)
#define SCU_PINMUX_X_IMAGE_DI7_REG     SCU_PINMUX8
#define SCU_PINMUX_X_IMAGE_DI7_POS     (28)
#define SCU_PINMUX_X_IMAGE_DI7_MSK     (0xFul << SCU_PINMUX_X_IMAGE_DI7_POS)
#define SCU_PINMUX_X_IMAGE_DI6_REG     SCU_PINMUX8
#define SCU_PINMUX_X_IMAGE_DI6_POS     (24)
#define SCU_PINMUX_X_IMAGE_DI6_MSK     (0xFul << SCU_PINMUX_X_IMAGE_DI6_POS)
#define SCU_PINMUX_X_IMAGE_DI5_REG     SCU_PINMUX8
#define SCU_PINMUX_X_IMAGE_DI5_POS     (20)
#define SCU_PINMUX_X_IMAGE_DI5_MSK     (0xFul << SCU_PINMUX_X_IMAGE_DI5_POS)
#define SCU_PINMUX_X_IMAGE_DI4_REG     SCU_PINMUX8
#define SCU_PINMUX_X_IMAGE_DI4_POS     (16)
#define SCU_PINMUX_X_IMAGE_DI4_MSK     (0xFul << SCU_PINMUX_X_IMAGE_DI4_POS)
#define SCU_PINMUX_X_IMAGE_DI3_REG     SCU_PINMUX8
#define SCU_PINMUX_X_IMAGE_DI3_POS     (12)
#define SCU_PINMUX_X_IMAGE_DI3_MSK     (0xFul << SCU_PINMUX_X_IMAGE_DI3_POS)
#define SCU_PINMUX_X_IMAGE_DI2_REG     SCU_PINMUX8
#define SCU_PINMUX_X_IMAGE_DI2_POS     (8)
#define SCU_PINMUX_X_IMAGE_DI2_MSK     (0xFul << SCU_PINMUX_X_IMAGE_DI2_POS)
#define SCU_PINMUX_X_IMAGE_DI1_REG     SCU_PINMUX8
#define SCU_PINMUX_X_IMAGE_DI1_POS     (4)
#define SCU_PINMUX_X_IMAGE_DI1_MSK     (0xFul << SCU_PINMUX_X_IMAGE_DI1_POS)
#define SCU_PINMUX_X_IMAGE_DI0_REG     SCU_PINMUX8
#define SCU_PINMUX_X_IMAGE_DI0_POS     (0)
#define SCU_PINMUX_X_IMAGE_DI0_MSK     (0xFul << SCU_PINMUX_X_IMAGE_DI0_POS)
#define SCU_PINMUX_X_IMAGE_MCLK_REG    SCU_PINMUX9
#define SCU_PINMUX_X_IMAGE_MCLK_POS    (12)
#define SCU_PINMUX_X_IMAGE_MCLK_MSK    (0xFul << SCU_PINMUX_X_IMAGE_MCLK_POS)
#define SCU_PINMUX_X_IMAGE_PCLK_REG    SCU_PINMUX9
#define SCU_PINMUX_X_IMAGE_PCLK_POS    (8)
#define SCU_PINMUX_X_IMAGE_PCLK_MSK    (0xFul << SCU_PINMUX_X_IMAGE_PCLK_POS)
#define SCU_PINMUX_X_IMAGE_VSYNC_REG   SCU_PINMUX9
#define SCU_PINMUX_X_IMAGE_VSYNC_POS   (4)
#define SCU_PINMUX_X_IMAGE_VSYNC_MSK   (0xFul << SCU_PINMUX_X_IMAGE_VSYNC_POS)
#define SCU_PINMUX_X_IMAGE_HSYNC_REG   SCU_PINMUX9
#define SCU_PINMUX_X_IMAGE_HSYNC_POS   (0)
#define SCU_PINMUX_X_IMAGE_HSYNC_MSK   (0xFul << SCU_PINMUX_X_IMAGE_HSYNC_POS)
#define SCU_PADDRV_X_OSPI_CSB0_REG     SCU_PADDRVOSPI
#define SCU_PADDRV_X_OSPI_CSB0_POS     (20)
#define SCU_PADDRV_X_OSPI_CSB0_MSK     (0xFul << SCU_PADDRV_X_OSPI_CSB0_POS)
#define SCU_PADDRV_X_OSPI_SD3_REG      SCU_PADDRVOSPI
#define SCU_PADDRV_X_OSPI_SD3_POS      (16)
#define SCU_PADDRV_X_OSPI_SD3_MSK      (0xFul << SCU_PADDRV_X_OSPI_SD3_POS)
#define SCU_PADDRV_X_OSPI_SD2_REG      SCU_PADDRVOSPI
#define SCU_PADDRV_X_OSPI_SD2_POS      (12)
#define SCU_PADDRV_X_OSPI_SD2_MSK      (0xFul << SCU_PADDRV_X_OSPI_SD2_POS)
#define SCU_PADDRV_X_OSPI_SD1_REG      SCU_PADDRVOSPI
#define SCU_PADDRV_X_OSPI_SD1_POS      (8)
#define SCU_PADDRV_X_OSPI_SD1_MSK      (0xFul << SCU_PADDRV_X_OSPI_SD1_POS)
#define SCU_PADDRV_X_OSPI_SD0_REG      SCU_PADDRVOSPI
#define SCU_PADDRV_X_OSPI_SD0_POS      (4)
#define SCU_PADDRV_X_OSPI_SD0_MSK      (0xFul << SCU_PADDRV_X_OSPI_SD0_POS)
#define SCU_PADDRV_X_OSPI_SCLK_REG     SCU_PADDRVOSPI
#define SCU_PADDRV_X_OSPI_SCLK_POS     (0)
#define SCU_PADDRV_X_OSPI_SCLK_MSK     (0xFul << SCU_PADDRV_X_OSPI_SCLK_POS)
#define SCU_PADDRV_X_SDIO_CMD_REG      SCU_PADDRV0
#define SCU_PADDRV_X_SDIO_CMD_POS      (28)
#define SCU_PADDRV_X_SDIO_CMD_MSK      (0xFul << SCU_PADDRV_X_SDIO_CMD_POS)
#define SCU_PADDRV_X_SDIO_CLK_REG      SCU_PADDRV0
#define SCU_PADDRV_X_SDIO_CLK_POS      (24)
#define SCU_PADDRV_X_SDIO_CLK_MSK      (0xFul << SCU_PADDRV_X_SDIO_CLK_POS)
#define SCU_PADDRV_X_OSPI_DQS_REG      SCU_PADDRV0
#define SCU_PADDRV_X_OSPI_DQS_POS      (20)
#define SCU_PADDRV_X_OSPI_DQS_MSK      (0xFul << SCU_PADDRV_X_OSPI_DQS_POS)
#define SCU_PADDRV_X_OSPI_SD7_REG      SCU_PADDRV0
#define SCU_PADDRV_X_OSPI_SD7_POS      (16)
#define SCU_PADDRV_X_OSPI_SD7_MSK      (0xFul << SCU_PADDRV_X_OSPI_SD7_POS)
#define SCU_PADDRV_X_OSPI_SD6_REG      SCU_PADDRV0
#define SCU_PADDRV_X_OSPI_SD6_POS      (12)
#define SCU_PADDRV_X_OSPI_SD6_MSK      (0xFul << SCU_PADDRV_X_OSPI_SD6_POS)
#define SCU_PADDRV_X_OSPI_SD5_REG      SCU_PADDRV0
#define SCU_PADDRV_X_OSPI_SD5_POS      (8)
#define SCU_PADDRV_X_OSPI_SD5_MSK      (0xFul << SCU_PADDRV_X_OSPI_SD5_POS)
#define SCU_PADDRV_X_OSPI_SD4_REG      SCU_PADDRV0
#define SCU_PADDRV_X_OSPI_SD4_POS      (4)
#define SCU_PADDRV_X_OSPI_SD4_MSK      (0xFul << SCU_PADDRV_X_OSPI_SD4_POS)
#define SCU_PADDRV_X_OSPI_CSB1_REG     SCU_PADDRV0
#define SCU_PADDRV_X_OSPI_CSB1_POS     (0)
#define SCU_PADDRV_X_OSPI_CSB1_MSK     (0xFul << SCU_PADDRV_X_OSPI_CSB1_POS)
#define SCU_PADDRV_X_SDIO_DATA7_REG    SCU_PADDRV1
#define SCU_PADDRV_X_SDIO_DATA7_POS    (28)
#define SCU_PADDRV_X_SDIO_DATA7_MSK    (0xFul << SCU_PADDRV_X_SDIO_DATA7_POS)
#define SCU_PADDRV_X_SDIO_DATA6_REG    SCU_PADDRV1
#define SCU_PADDRV_X_SDIO_DATA6_POS    (24)
#define SCU_PADDRV_X_SDIO_DATA6_MSK    (0xFul << SCU_PADDRV_X_SDIO_DATA6_POS)
#define SCU_PADDRV_X_SDIO_DATA5_REG    SCU_PADDRV1
#define SCU_PADDRV_X_SDIO_DATA5_POS    (20)
#define SCU_PADDRV_X_SDIO_DATA5_MSK    (0xFul << SCU_PADDRV_X_SDIO_DATA5_POS)
#define SCU_PADDRV_X_SDIO_DATA4_REG    SCU_PADDRV1
#define SCU_PADDRV_X_SDIO_DATA4_POS    (16)
#define SCU_PADDRV_X_SDIO_DATA4_MSK    (0xFul << SCU_PADDRV_X_SDIO_DATA4_POS)
#define SCU_PADDRV_X_SDIO_DATA3_REG    SCU_PADDRV1
#define SCU_PADDRV_X_SDIO_DATA3_POS    (12)
#define SCU_PADDRV_X_SDIO_DATA3_MSK    (0xFul << SCU_PADDRV_X_SDIO_DATA3_POS)
#define SCU_PADDRV_X_SDIO_DATA2_REG    SCU_PADDRV1
#define SCU_PADDRV_X_SDIO_DATA2_POS    (8)
#define SCU_PADDRV_X_SDIO_DATA2_MSK    (0xFul << SCU_PADDRV_X_SDIO_DATA2_POS)
#define SCU_PADDRV_X_SDIO_DATA1_REG    SCU_PADDRV1
#define SCU_PADDRV_X_SDIO_DATA1_POS    (4)
#define SCU_PADDRV_X_SDIO_DATA1_MSK    (0xFul << SCU_PADDRV_X_SDIO_DATA1_POS)
#define SCU_PADDRV_X_SDIO_DATA0_REG    SCU_PADDRV1
#define SCU_PADDRV_X_SDIO_DATA0_POS    (0)
#define SCU_PADDRV_X_SDIO_DATA0_MSK    (0xFul << SCU_PADDRV_X_SDIO_DATA0_POS)
#define SCU_PADDRV_X_LCD_SPI_SD_REG    SCU_PADDRV2
#define SCU_PADDRV_X_LCD_SPI_SD_POS    (28)
#define SCU_PADDRV_X_LCD_SPI_SD_MSK    (0xFul << SCU_PADDRV_X_LCD_SPI_SD_POS)
#define SCU_PADDRV_X_LCD_SPI_SCK_REG   SCU_PADDRV2
#define SCU_PADDRV_X_LCD_SPI_SCK_POS   (24)
#define SCU_PADDRV_X_LCD_SPI_SCK_MSK   (0xFul << SCU_PADDRV_X_LCD_SPI_SCK_POS)
#define SCU_PADDRV_X_LCD_RESETB_REG    SCU_PADDRV2
#define SCU_PADDRV_X_LCD_RESETB_POS    (20)
#define SCU_PADDRV_X_LCD_RESETB_MSK    (0xFul << SCU_PADDRV_X_LCD_RESETB_POS)
#define SCU_PADDRV_X_JTAG_GPIO_SEL_REG SCU_PADDRV2
#define SCU_PADDRV_X_JTAG_GPIO_SEL_POS (16)
#define SCU_PADDRV_X_JTAG_GPIO_SEL_MSK (0xFul << SCU_PADDRV_X_JTAG_GPIO_SEL_POS)
#define SCU_PADDRV_X_CPU_TDO_REG       SCU_PADDRV2
#define SCU_PADDRV_X_CPU_TDO_POS       (12)
#define SCU_PADDRV_X_CPU_TDO_MSK       (0xFul << SCU_PADDRV_X_CPU_TDO_POS)
#define SCU_PADDRV_X_CPU_TDI_REG       SCU_PADDRV2
#define SCU_PADDRV_X_CPU_TDI_POS       (8)
#define SCU_PADDRV_X_CPU_TDI_MSK       (0xFul << SCU_PADDRV_X_CPU_TDI_POS)
#define SCU_PADDRV_X_CPU_TCK_REG       SCU_PADDRV2
#define SCU_PADDRV_X_CPU_TCK_POS       (4)
#define SCU_PADDRV_X_CPU_TCK_MSK       (0xFul << SCU_PADDRV_X_CPU_TCK_POS)
#define SCU_PADDRV_X_CPU_TMS_REG       SCU_PADDRV2
#define SCU_PADDRV_X_CPU_TMS_POS       (0)
#define SCU_PADDRV_X_CPU_TMS_MSK       (0xFul << SCU_PADDRV_X_CPU_TMS_POS)
#define SCU_PADDRV_X_I2C0_SDA_REG      SCU_PADDRV3
#define SCU_PADDRV_X_I2C0_SDA_POS      (28)
#define SCU_PADDRV_X_I2C0_SDA_MSK      (0xFul << SCU_PADDRV_X_I2C0_SDA_POS)
#define SCU_PADDRV_X_I2C0_SCL_REG      SCU_PADDRV3
#define SCU_PADDRV_X_I2C0_SCL_POS      (24)
#define SCU_PADDRV_X_I2C0_SCL_MSK      (0xFul << SCU_PADDRV_X_I2C0_SCL_POS)
#define SCU_PADDRV_X_UART0_CTS_ISP_REG SCU_PADDRV3
#define SCU_PADDRV_X_UART0_CTS_ISP_POS (20)
#define SCU_PADDRV_X_UART0_CTS_ISP_MSK (0xFul << SCU_PADDRV_X_UART0_CTS_ISP_POS)
#define SCU_PADDRV_X_UART0_RTS_ISP_REG SCU_PADDRV3
#define SCU_PADDRV_X_UART0_RTS_ISP_POS (16)
#define SCU_PADDRV_X_UART0_RTS_ISP_MSK (0xFul << SCU_PADDRV_X_UART0_RTS_ISP_POS)
#define SCU_PADDRV_X_UART0_RXD_ISP_REG SCU_PADDRV3
#define SCU_PADDRV_X_UART0_RXD_ISP_POS (12)
#define SCU_PADDRV_X_UART0_RXD_ISP_MSK (0xFul << SCU_PADDRV_X_UART0_RXD_ISP_POS)
#define SCU_PADDRV_X_UART0_TXD_ISP_REG SCU_PADDRV3
#define SCU_PADDRV_X_UART0_TXD_ISP_POS (8)
#define SCU_PADDRV_X_UART0_TXD_ISP_MSK (0xFul << SCU_PADDRV_X_UART0_TXD_ISP_POS)
#define SCU_PADDRV_X_LCD_SPI_DCX_REG   SCU_PADDRV3
#define SCU_PADDRV_X_LCD_SPI_DCX_POS   (4)
#define SCU_PADDRV_X_LCD_SPI_DCX_MSK   (0xFul << SCU_PADDRV_X_LCD_SPI_DCX_POS)
#define SCU_PADDRV_X_LCD_SPI_CSB_REG   SCU_PADDRV3
#define SCU_PADDRV_X_LCD_SPI_CSB_POS   (0)
#define SCU_PADDRV_X_LCD_SPI_CSB_MSK   (0xFul << SCU_PADDRV_X_LCD_SPI_CSB_POS)
#define SCU_PADDRV_X_SPI0_CSB0_REG     SCU_PADDRV4
#define SCU_PADDRV_X_SPI0_CSB0_POS     (28)
#define SCU_PADDRV_X_SPI0_CSB0_MSK     (0xFul << SCU_PADDRV_X_SPI0_CSB0_POS)
#define SCU_PADDRV_X_SPI0_SDO_REG      SCU_PADDRV4
#define SCU_PADDRV_X_SPI0_SDO_POS      (24)
#define SCU_PADDRV_X_SPI0_SDO_MSK      (0xFul << SCU_PADDRV_X_SPI0_SDO_POS)
#define SCU_PADDRV_X_SPI0_SDI_REG      SCU_PADDRV4
#define SCU_PADDRV_X_SPI0_SDI_POS      (20)
#define SCU_PADDRV_X_SPI0_SDI_MSK      (0xFul << SCU_PADDRV_X_SPI0_SDI_POS)
#define SCU_PADDRV_X_SPI0_SCK_REG      SCU_PADDRV4
#define SCU_PADDRV_X_SPI0_SCK_POS      (16)
#define SCU_PADDRV_X_SPI0_SCK_MSK      (0xFul << SCU_PADDRV_X_SPI0_SCK_POS)
#define SCU_PADDRV_X_UART1_CTS_REG     SCU_PADDRV4
#define SCU_PADDRV_X_UART1_CTS_POS     (12)
#define SCU_PADDRV_X_UART1_CTS_MSK     (0xFul << SCU_PADDRV_X_UART1_CTS_POS)
#define SCU_PADDRV_X_UART1_RTS_REG     SCU_PADDRV4
#define SCU_PADDRV_X_UART1_RTS_POS     (8)
#define SCU_PADDRV_X_UART1_RTS_MSK     (0xFul << SCU_PADDRV_X_UART1_RTS_POS)
#define SCU_PADDRV_X_UART1_RXD_REG     SCU_PADDRV4
#define SCU_PADDRV_X_UART1_RXD_POS     (4)
#define SCU_PADDRV_X_UART1_RXD_MSK     (0xFul << SCU_PADDRV_X_UART1_RXD_POS)
#define SCU_PADDRV_X_UART1_TXD_REG     SCU_PADDRV4
#define SCU_PADDRV_X_UART1_TXD_POS     (0)
#define SCU_PADDRV_X_UART1_TXD_MSK     (0xFul << SCU_PADDRV_X_UART1_TXD_POS)
#define SCU_PADDRV_X_I2S0_BCLK_REG     SCU_PADDRV5
#define SCU_PADDRV_X_I2S0_BCLK_POS     (24)
#define SCU_PADDRV_X_I2S0_BCLK_MSK     (0xFul << SCU_PADDRV_X_I2S0_BCLK_POS)
#define SCU_PADDRV_X_I2S0_WS_REG       SCU_PADDRV5
#define SCU_PADDRV_X_I2S0_WS_POS       (20)
#define SCU_PADDRV_X_I2S0_WS_MSK       (0xFul << SCU_PADDRV_X_I2S0_WS_POS)
#define SCU_PADDRV_X_SPI1_CSB0_REG     SCU_PADDRV5
#define SCU_PADDRV_X_SPI1_CSB0_POS     (16)
#define SCU_PADDRV_X_SPI1_CSB0_MSK     (0xFul << SCU_PADDRV_X_SPI1_CSB0_POS)
#define SCU_PADDRV_X_SPI1_SDO_REG      SCU_PADDRV5
#define SCU_PADDRV_X_SPI1_SDO_POS      (12)
#define SCU_PADDRV_X_SPI1_SDO_MSK      (0xFul << SCU_PADDRV_X_SPI1_SDO_POS)
#define SCU_PADDRV_X_SPI1_SDI_REG      SCU_PADDRV5
#define SCU_PADDRV_X_SPI1_SDI_POS      (8)
#define SCU_PADDRV_X_SPI1_SDI_MSK      (0xFul << SCU_PADDRV_X_SPI1_SDI_POS)
#define SCU_PADDRV_X_SPI1_SCK_REG      SCU_PADDRV5
#define SCU_PADDRV_X_SPI1_SCK_POS      (4)
#define SCU_PADDRV_X_SPI1_SCK_MSK      (0xFul << SCU_PADDRV_X_SPI1_SCK_POS)
#define SCU_PADDRV_X_SPI0_CSB1_REG     SCU_PADDRV5
#define SCU_PADDRV_X_SPI0_CSB1_POS     (0)
#define SCU_PADDRV_X_SPI0_CSB1_MSK     (0xFul << SCU_PADDRV_X_SPI0_CSB1_POS)
#define SCU_PADDRV_X_LED_PWM1_REG      SCU_PADDRV6
#define SCU_PADDRV_X_LED_PWM1_POS      (28)
#define SCU_PADDRV_X_LED_PWM1_MSK      (0xFul << SCU_PADDRV_X_LED_PWM1_POS)
#define SCU_PADDRV_X_LED_PWM0_REG      SCU_PADDRV6
#define SCU_PADDRV_X_LED_PWM0_POS      (24)
#define SCU_PADDRV_X_LED_PWM0_MSK      (0xFul << SCU_PADDRV_X_LED_PWM0_POS)
#define SCU_PADDRV_X_I2S1_SOUT_REG     SCU_PADDRV6
#define SCU_PADDRV_X_I2S1_SOUT_POS     (20)
#define SCU_PADDRV_X_I2S1_SOUT_MSK     (0xFul << SCU_PADDRV_X_I2S1_SOUT_POS)
#define SCU_PADDRV_X_I2S1_SIN_REG      SCU_PADDRV6
#define SCU_PADDRV_X_I2S1_SIN_POS      (16)
#define SCU_PADDRV_X_I2S1_SIN_MSK      (0xFul << SCU_PADDRV_X_I2S1_SIN_POS)
#define SCU_PADDRV_X_I2S1_BCLK_REG     SCU_PADDRV6
#define SCU_PADDRV_X_I2S1_BCLK_POS     (12)
#define SCU_PADDRV_X_I2S1_BCLK_MSK     (0xFul << SCU_PADDRV_X_I2S1_BCLK_POS)
#define SCU_PADDRV_X_I2S1_WS_REG       SCU_PADDRV6
#define SCU_PADDRV_X_I2S1_WS_POS       (8)
#define SCU_PADDRV_X_I2S1_WS_MSK       (0xFul << SCU_PADDRV_X_I2S1_WS_POS)
#define SCU_PADDRV_X_I2S0_MCLK_REG     SCU_PADDRV6
#define SCU_PADDRV_X_I2S0_MCLK_POS     (4)
#define SCU_PADDRV_X_I2S0_MCLK_MSK     (0xFul << SCU_PADDRV_X_I2S0_MCLK_POS)
#define SCU_PADDRV_X_I2S0_SD_REG       SCU_PADDRV6
#define SCU_PADDRV_X_I2S0_SD_POS       (0)
#define SCU_PADDRV_X_I2S0_SD_MSK       (0xFul << SCU_PADDRV_X_I2S0_SD_POS)
#define SCU_PADDRV_X_SPI2_CSB0_REG     SCU_PADDRV7
#define SCU_PADDRV_X_SPI2_CSB0_POS     (28)
#define SCU_PADDRV_X_SPI2_CSB0_MSK     (0xFul << SCU_PADDRV_X_SPI2_CSB0_POS)
#define SCU_PADDRV_X_SPI2_SDO_REG      SCU_PADDRV7
#define SCU_PADDRV_X_SPI2_SDO_POS      (24)
#define SCU_PADDRV_X_SPI2_SDO_MSK      (0xFul << SCU_PADDRV_X_SPI2_SDO_POS)
#define SCU_PADDRV_X_SPI2_SDI_REG      SCU_PADDRV7
#define SCU_PADDRV_X_SPI2_SDI_POS      (20)
#define SCU_PADDRV_X_SPI2_SDI_MSK      (0xFul << SCU_PADDRV_X_SPI2_SDI_POS)
#define SCU_PADDRV_X_SPI2_SCK_REG      SCU_PADDRV7
#define SCU_PADDRV_X_SPI2_SCK_POS      (16)
#define SCU_PADDRV_X_SPI2_SCK_MSK      (0xFul << SCU_PADDRV_X_SPI2_SCK_POS)
#define SCU_PADDRV_X_PDM0_DIN_REG      SCU_PADDRV7
#define SCU_PADDRV_X_PDM0_DIN_POS      (12)
#define SCU_PADDRV_X_PDM0_DIN_MSK      (0xFul << SCU_PADDRV_X_PDM0_DIN_POS)
#define SCU_PADDRV_X_PDM0_CLK_REG      SCU_PADDRV7
#define SCU_PADDRV_X_PDM0_CLK_POS      (8)
#define SCU_PADDRV_X_PDM0_CLK_MSK      (0xFul << SCU_PADDRV_X_PDM0_CLK_POS)
#define SCU_PADDRV_X_LED_PWM3_REG      SCU_PADDRV7
#define SCU_PADDRV_X_LED_PWM3_POS      (4)
#define SCU_PADDRV_X_LED_PWM3_MSK      (0xFul << SCU_PADDRV_X_LED_PWM3_POS)
#define SCU_PADDRV_X_LED_PWM2_REG      SCU_PADDRV7
#define SCU_PADDRV_X_LED_PWM2_POS      (0)
#define SCU_PADDRV_X_LED_PWM2_MSK      (0xFul << SCU_PADDRV_X_LED_PWM2_POS)
#define SCU_PADDRV_X_IMAGE_DI7_REG     SCU_PADDRV8
#define SCU_PADDRV_X_IMAGE_DI7_POS     (28)
#define SCU_PADDRV_X_IMAGE_DI7_MSK     (0xFul << SCU_PADDRV_X_IMAGE_DI7_POS)
#define SCU_PADDRV_X_IMAGE_DI6_REG     SCU_PADDRV8
#define SCU_PADDRV_X_IMAGE_DI6_POS     (24)
#define SCU_PADDRV_X_IMAGE_DI6_MSK     (0xFul << SCU_PADDRV_X_IMAGE_DI6_POS)
#define SCU_PADDRV_X_IMAGE_DI5_REG     SCU_PADDRV8
#define SCU_PADDRV_X_IMAGE_DI5_POS     (20)
#define SCU_PADDRV_X_IMAGE_DI5_MSK     (0xFul << SCU_PADDRV_X_IMAGE_DI5_POS)
#define SCU_PADDRV_X_IMAGE_DI4_REG     SCU_PADDRV8
#define SCU_PADDRV_X_IMAGE_DI4_POS     (16)
#define SCU_PADDRV_X_IMAGE_DI4_MSK     (0xFul << SCU_PADDRV_X_IMAGE_DI4_POS)
#define SCU_PADDRV_X_IMAGE_DI3_REG     SCU_PADDRV8
#define SCU_PADDRV_X_IMAGE_DI3_POS     (12)
#define SCU_PADDRV_X_IMAGE_DI3_MSK     (0xFul << SCU_PADDRV_X_IMAGE_DI3_POS)
#define SCU_PADDRV_X_IMAGE_DI2_REG     SCU_PADDRV8
#define SCU_PADDRV_X_IMAGE_DI2_POS     (8)
#define SCU_PADDRV_X_IMAGE_DI2_MSK     (0xFul << SCU_PADDRV_X_IMAGE_DI2_POS)
#define SCU_PADDRV_X_IMAGE_DI1_REG     SCU_PADDRV8
#define SCU_PADDRV_X_IMAGE_DI1_POS     (4)
#define SCU_PADDRV_X_IMAGE_DI1_MSK     (0xFul << SCU_PADDRV_X_IMAGE_DI1_POS)
#define SCU_PADDRV_X_IMAGE_DI0_REG     SCU_PADDRV8
#define SCU_PADDRV_X_IMAGE_DI0_POS     (0)
#define SCU_PADDRV_X_IMAGE_DI0_MSK     (0xFul << SCU_PADDRV_X_IMAGE_DI0_POS)
#define SCU_PADDRV_X_IMAGE_MCLK_REG    SCU_PADDRV9
#define SCU_PADDRV_X_IMAGE_MCLK_POS    (12)
#define SCU_PADDRV_X_IMAGE_MCLK_MSK    (0xFul << SCU_PADDRV_X_IMAGE_MCLK_POS)
#define SCU_PADDRV_X_IMAGE_PCLK_REG    SCU_PADDRV9
#define SCU_PADDRV_X_IMAGE_PCLK_POS    (8)
#define SCU_PADDRV_X_IMAGE_PCLK_MSK    (0xFul << SCU_PADDRV_X_IMAGE_PCLK_POS)
#define SCU_PADDRV_X_IMAGE_VSYNC_REG   SCU_PADDRV9
#define SCU_PADDRV_X_IMAGE_VSYNC_POS   (4)
#define SCU_PADDRV_X_IMAGE_VSYNC_MSK   (0xFul << SCU_PADDRV_X_IMAGE_VSYNC_POS)
#define SCU_PADDRV_X_IMAGE_HSYNC_REG   SCU_PADDRV9
#define SCU_PADDRV_X_IMAGE_HSYNC_POS   (0)
#define SCU_PADDRV_X_IMAGE_HSYNC_MSK   (0xFul << SCU_PADDRV_X_IMAGE_HSYNC_POS)
#define SCU_PADCTRL_X_OSPI_CSB0_REG    SCU_PADCTRLOSPI
#define SCU_PADCTRL_X_OSPI_CSB0_POS    (20)
#define SCU_PADCTRL_X_OSPI_CSB0_MSK    (0xFul << SCU_PADCTRL_X_OSPI_CSB0_POS)
#define SCU_PADCTRL_X_OSPI_SD3_REG     SCU_PADCTRLOSPI
#define SCU_PADCTRL_X_OSPI_SD3_POS     (16)
#define SCU_PADCTRL_X_OSPI_SD3_MSK     (0xFul << SCU_PADCTRL_X_OSPI_SD3_POS)
#define SCU_PADCTRL_X_OSPI_SD2_REG     SCU_PADCTRLOSPI
#define SCU_PADCTRL_X_OSPI_SD2_POS     (12)
#define SCU_PADCTRL_X_OSPI_SD2_MSK     (0xFul << SCU_PADCTRL_X_OSPI_SD2_POS)
#define SCU_PADCTRL_X_OSPI_SD1_REG     SCU_PADCTRLOSPI
#define SCU_PADCTRL_X_OSPI_SD1_POS     (8)
#define SCU_PADCTRL_X_OSPI_SD1_MSK     (0xFul << SCU_PADCTRL_X_OSPI_SD1_POS)
#define SCU_PADCTRL_X_OSPI_SD0_REG     SCU_PADCTRLOSPI
#define SCU_PADCTRL_X_OSPI_SD0_POS     (4)
#define SCU_PADCTRL_X_OSPI_SD0_MSK     (0xFul << SCU_PADCTRL_X_OSPI_SD0_POS)
#define SCU_PADCTRL_X_OSPI_SCLK_REG    SCU_PADCTRLOSPI
#define SCU_PADCTRL_X_OSPI_SCLK_POS    (0)
#define SCU_PADCTRL_X_OSPI_SCLK_MSK    (0xFul << SCU_PADCTRL_X_OSPI_SCLK_POS)
#define SCU_PADCTRL_X_SDIO_CMD_REG     SCU_PADCTRL0
#define SCU_PADCTRL_X_SDIO_CMD_POS     (28)
#define SCU_PADCTRL_X_SDIO_CMD_MSK     (0xFul << SCU_PADCTRL_X_SDIO_CMD_POS)
#define SCU_PADCTRL_X_SDIO_CLK_REG     SCU_PADCTRL0
#define SCU_PADCTRL_X_SDIO_CLK_POS     (24)
#define SCU_PADCTRL_X_SDIO_CLK_MSK     (0xFul << SCU_PADCTRL_X_SDIO_CLK_POS)
#define SCU_PADCTRL_X_OSPI_DQS_REG     SCU_PADCTRL0
#define SCU_PADCTRL_X_OSPI_DQS_POS     (20)
#define SCU_PADCTRL_X_OSPI_DQS_MSK     (0xFul << SCU_PADCTRL_X_OSPI_DQS_POS)
#define SCU_PADCTRL_X_OSPI_SD7_REG     SCU_PADCTRL0
#define SCU_PADCTRL_X_OSPI_SD7_POS     (16)
#define SCU_PADCTRL_X_OSPI_SD7_MSK     (0xFul << SCU_PADCTRL_X_OSPI_SD7_POS)
#define SCU_PADCTRL_X_OSPI_SD6_REG     SCU_PADCTRL0
#define SCU_PADCTRL_X_OSPI_SD6_POS     (12)
#define SCU_PADCTRL_X_OSPI_SD6_MSK     (0xFul << SCU_PADCTRL_X_OSPI_SD6_POS)
#define SCU_PADCTRL_X_OSPI_SD5_REG     SCU_PADCTRL0
#define SCU_PADCTRL_X_OSPI_SD5_POS     (8)
#define SCU_PADCTRL_X_OSPI_SD5_MSK     (0xFul << SCU_PADCTRL_X_OSPI_SD5_POS)
#define SCU_PADCTRL_X_OSPI_SD4_REG     SCU_PADCTRL0
#define SCU_PADCTRL_X_OSPI_SD4_POS     (4)
#define SCU_PADCTRL_X_OSPI_SD4_MSK     (0xFul << SCU_PADCTRL_X_OSPI_SD4_POS)
#define SCU_PADCTRL_X_OSPI_CSB1_REG    SCU_PADCTRL0
#define SCU_PADCTRL_X_OSPI_CSB1_POS    (0)
#define SCU_PADCTRL_X_OSPI_CSB1_MSK    (0xFul << SCU_PADCTRL_X_OSPI_CSB1_POS)
#define SCU_PADCTRL_X_SDIO_DATA7_REG   SCU_PADCTRL1
#define SCU_PADCTRL_X_SDIO_DATA7_POS   (28)
#define SCU_PADCTRL_X_SDIO_DATA7_MSK   (0xFul << SCU_PADCTRL_X_SDIO_DATA7_POS)
#define SCU_PADCTRL_X_SDIO_DATA6_REG   SCU_PADCTRL1
#define SCU_PADCTRL_X_SDIO_DATA6_POS   (24)
#define SCU_PADCTRL_X_SDIO_DATA6_MSK   (0xFul << SCU_PADCTRL_X_SDIO_DATA6_POS)
#define SCU_PADCTRL_X_SDIO_DATA5_REG   SCU_PADCTRL1
#define SCU_PADCTRL_X_SDIO_DATA5_POS   (20)
#define SCU_PADCTRL_X_SDIO_DATA5_MSK   (0xFul << SCU_PADCTRL_X_SDIO_DATA5_POS)
#define SCU_PADCTRL_X_SDIO_DATA4_REG   SCU_PADCTRL1
#define SCU_PADCTRL_X_SDIO_DATA4_POS   (16)
#define SCU_PADCTRL_X_SDIO_DATA4_MSK   (0xFul << SCU_PADCTRL_X_SDIO_DATA4_POS)
#define SCU_PADCTRL_X_SDIO_DATA3_REG   SCU_PADCTRL1
#define SCU_PADCTRL_X_SDIO_DATA3_POS   (12)
#define SCU_PADCTRL_X_SDIO_DATA3_MSK   (0xFul << SCU_PADCTRL_X_SDIO_DATA3_POS)
#define SCU_PADCTRL_X_SDIO_DATA2_REG   SCU_PADCTRL1
#define SCU_PADCTRL_X_SDIO_DATA2_POS   (8)
#define SCU_PADCTRL_X_SDIO_DATA2_MSK   (0xFul << SCU_PADCTRL_X_SDIO_DATA2_POS)
#define SCU_PADCTRL_X_SDIO_DATA1_REG   SCU_PADCTRL1
#define SCU_PADCTRL_X_SDIO_DATA1_POS   (4)
#define SCU_PADCTRL_X_SDIO_DATA1_MSK   (0xFul << SCU_PADCTRL_X_SDIO_DATA1_POS)
#define SCU_PADCTRL_X_SDIO_DATA0_REG   SCU_PADCTRL1
#define SCU_PADCTRL_X_SDIO_DATA0_POS   (0)
#define SCU_PADCTRL_X_SDIO_DATA0_MSK   (0xFul << SCU_PADCTRL_X_SDIO_DATA0_POS)
#define SCU_PADCTRL_X_LCD_SPI_SD_REG   SCU_PADCTRL2
#define SCU_PADCTRL_X_LCD_SPI_SD_POS   (28)
#define SCU_PADCTRL_X_LCD_SPI_SD_MSK   (0xFul << SCU_PADCTRL_X_LCD_SPI_SD_POS)
#define SCU_PADCTRL_X_LCD_SPI_SCK_REG  SCU_PADCTRL2
#define SCU_PADCTRL_X_LCD_SPI_SCK_POS  (24)
#define SCU_PADCTRL_X_LCD_SPI_SCK_MSK  (0xFul << SCU_PADCTRL_X_LCD_SPI_SCK_POS)
#define SCU_PADCTRL_X_LCD_RESETB_REG   SCU_PADCTRL2
#define SCU_PADCTRL_X_LCD_RESETB_POS   (20)
#define SCU_PADCTRL_X_LCD_RESETB_MSK   (0xFul << SCU_PADCTRL_X_LCD_RESETB_POS)
#define SCU_PADCTRL_X_JTAG_GPIO_SEL_REG SCU_PADCTRL2
#define SCU_PADCTRL_X_JTAG_GPIO_SEL_POS (16)
#define SCU_PADCTRL_X_JTAG_GPIO_SEL_MSK (0xFul << SCU_PADCTRL_X_JTAG_GPIO_SEL_POS)
#define SCU_PADCTRL_X_CPU_TDO_REG      SCU_PADCTRL2
#define SCU_PADCTRL_X_CPU_TDO_POS      (12)
#define SCU_PADCTRL_X_CPU_TDO_MSK      (0xFul << SCU_PADCTRL_X_CPU_TDO_POS)
#define SCU_PADCTRL_X_CPU_TDI_REG      SCU_PADCTRL2
#define SCU_PADCTRL_X_CPU_TDI_POS      (8)
#define SCU_PADCTRL_X_CPU_TDI_MSK      (0xFul << SCU_PADCTRL_X_CPU_TDI_POS)
#define SCU_PADCTRL_X_CPU_TCK_REG      SCU_PADCTRL2
#define SCU_PADCTRL_X_CPU_TCK_POS      (4)
#define SCU_PADCTRL_X_CPU_TCK_MSK      (0xFul << SCU_PADCTRL_X_CPU_TCK_POS)
#define SCU_PADCTRL_X_CPU_TMS_REG      SCU_PADCTRL2
#define SCU_PADCTRL_X_CPU_TMS_POS      (0)
#define SCU_PADCTRL_X_CPU_TMS_MSK      (0xFul << SCU_PADCTRL_X_CPU_TMS_POS)
#define SCU_PADCTRL_X_I2C0_SDA_REG     SCU_PADCTRL3
#define SCU_PADCTRL_X_I2C0_SDA_POS     (28)
#define SCU_PADCTRL_X_I2C0_SDA_MSK     (0xFul << SCU_PADCTRL_X_I2C0_SDA_POS)
#define SCU_PADCTRL_X_I2C0_SCL_REG     SCU_PADCTRL3
#define SCU_PADCTRL_X_I2C0_SCL_POS     (24)
#define SCU_PADCTRL_X_I2C0_SCL_MSK     (0xFul << SCU_PADCTRL_X_I2C0_SCL_POS)
#define SCU_PADCTRL_X_UART0_CTS_ISP_REG SCU_PADCTRL3
#define SCU_PADCTRL_X_UART0_CTS_ISP_POS (20)
#define SCU_PADCTRL_X_UART0_CTS_ISP_MSK (0xFul << SCU_PADCTRL_X_UART0_CTS_ISP_POS)
#define SCU_PADCTRL_X_UART0_RTS_ISP_REG SCU_PADCTRL3
#define SCU_PADCTRL_X_UART0_RTS_ISP_POS (16)
#define SCU_PADCTRL_X_UART0_RTS_ISP_MSK (0xFul << SCU_PADCTRL_X_UART0_RTS_ISP_POS)
#define SCU_PADCTRL_X_UART0_RXD_ISP_REG SCU_PADCTRL3
#define SCU_PADCTRL_X_UART0_RXD_ISP_POS (12)
#define SCU_PADCTRL_X_UART0_RXD_ISP_MSK (0xFul << SCU_PADCTRL_X_UART0_RXD_ISP_POS)
#define SCU_PADCTRL_X_UART0_TXD_ISP_REG SCU_PADCTRL3
#define SCU_PADCTRL_X_UART0_TXD_ISP_POS (8)
#define SCU_PADCTRL_X_UART0_TXD_ISP_MSK (0xFul << SCU_PADCTRL_X_UART0_TXD_ISP_POS)
#define SCU_PADCTRL_X_LCD_SPI_DCX_REG  SCU_PADCTRL3
#define SCU_PADCTRL_X_LCD_SPI_DCX_POS  (4)
#define SCU_PADCTRL_X_LCD_SPI_DCX_MSK  (0xFul << SCU_PADCTRL_X_LCD_SPI_DCX_POS)
#define SCU_PADCTRL_X_LCD_SPI_CSB_REG  SCU_PADCTRL3
#define SCU_PADCTRL_X_LCD_SPI_CSB_POS  (0)
#define SCU_PADCTRL_X_LCD_SPI_CSB_MSK  (0xFul << SCU_PADCTRL_X_LCD_SPI_CSB_POS)
#define SCU_PADCTRL_X_SPI0_CSB0_REG    SCU_PADCTRL4
#define SCU_PADCTRL_X_SPI0_CSB0_POS    (28)
#define SCU_PADCTRL_X_SPI0_CSB0_MSK    (0xFul << SCU_PADCTRL_X_SPI0_CSB0_POS)
#define SCU_PADCTRL_X_SPI0_SDO_REG     SCU_PADCTRL4
#define SCU_PADCTRL_X_SPI0_SDO_POS     (24)
#define SCU_PADCTRL_X_SPI0_SDO_MSK     (0xFul << SCU_PADCTRL_X_SPI0_SDO_POS)
#define SCU_PADCTRL_X_SPI0_SDI_REG     SCU_PADCTRL4
#define SCU_PADCTRL_X_SPI0_SDI_POS     (20)
#define SCU_PADCTRL_X_SPI0_SDI_MSK     (0xFul << SCU_PADCTRL_X_SPI0_SDI_POS)
#define SCU_PADCTRL_X_SPI0_SCK_REG     SCU_PADCTRL4
#define SCU_PADCTRL_X_SPI0_SCK_POS     (16)
#define SCU_PADCTRL_X_SPI0_SCK_MSK     (0xFul << SCU_PADCTRL_X_SPI0_SCK_POS)
#define SCU_PADCTRL_X_UART1_CTS_REG    SCU_PADCTRL4
#define SCU_PADCTRL_X_UART1_CTS_POS    (12)
#define SCU_PADCTRL_X_UART1_CTS_MSK    (0xFul << SCU_PADCTRL_X_UART1_CTS_POS)
#define SCU_PADCTRL_X_UART1_RTS_REG    SCU_PADCTRL4
#define SCU_PADCTRL_X_UART1_RTS_POS    (8)
#define SCU_PADCTRL_X_UART1_RTS_MSK    (0xFul << SCU_PADCTRL_X_UART1_RTS_POS)
#define SCU_PADCTRL_X_UART1_RXD_REG    SCU_PADCTRL4
#define SCU_PADCTRL_X_UART1_RXD_POS    (4)
#define SCU_PADCTRL_X_UART1_RXD_MSK    (0xFul << SCU_PADCTRL_X_UART1_RXD_POS)
#define SCU_PADCTRL_X_UART1_TXD_REG    SCU_PADCTRL4
#define SCU_PADCTRL_X_UART1_TXD_POS    (0)
#define SCU_PADCTRL_X_UART1_TXD_MSK    (0xFul << SCU_PADCTRL_X_UART1_TXD_POS)
#define SCU_PADCTRL_X_I2S0_BCLK_REG    SCU_PADCTRL5
#define SCU_PADCTRL_X_I2S0_BCLK_POS    (24)
#define SCU_PADCTRL_X_I2S0_BCLK_MSK    (0xFul << SCU_PADCTRL_X_I2S0_BCLK_POS)
#define SCU_PADCTRL_X_I2S0_WS_REG      SCU_PADCTRL5
#define SCU_PADCTRL_X_I2S0_WS_POS      (20)
#define SCU_PADCTRL_X_I2S0_WS_MSK      (0xFul << SCU_PADCTRL_X_I2S0_WS_POS)
#define SCU_PADCTRL_X_SPI1_CSB0_REG    SCU_PADCTRL5
#define SCU_PADCTRL_X_SPI1_CSB0_POS    (16)
#define SCU_PADCTRL_X_SPI1_CSB0_MSK    (0xFul << SCU_PADCTRL_X_SPI1_CSB0_POS)
#define SCU_PADCTRL_X_SPI1_SDO_REG     SCU_PADCTRL5
#define SCU_PADCTRL_X_SPI1_SDO_POS     (12)
#define SCU_PADCTRL_X_SPI1_SDO_MSK     (0xFul << SCU_PADCTRL_X_SPI1_SDO_POS)
#define SCU_PADCTRL_X_SPI1_SDI_REG     SCU_PADCTRL5
#define SCU_PADCTRL_X_SPI1_SDI_POS     (8)
#define SCU_PADCTRL_X_SPI1_SDI_MSK     (0xFul << SCU_PADCTRL_X_SPI1_SDI_POS)
#define SCU_PADCTRL_X_SPI1_SCK_REG     SCU_PADCTRL5
#define SCU_PADCTRL_X_SPI1_SCK_POS     (4)
#define SCU_PADCTRL_X_SPI1_SCK_MSK     (0xFul << SCU_PADCTRL_X_SPI1_SCK_POS)
#define SCU_PADCTRL_X_SPI0_CSB1_REG    SCU_PADCTRL5
#define SCU_PADCTRL_X_SPI0_CSB1_POS    (0)
#define SCU_PADCTRL_X_SPI0_CSB1_MSK    (0xFul << SCU_PADCTRL_X_SPI0_CSB1_POS)
#define SCU_PADCTRL_X_LED_PWM1_REG     SCU_PADCTRL6
#define SCU_PADCTRL_X_LED_PWM1_POS     (28)
#define SCU_PADCTRL_X_LED_PWM1_MSK     (0xFul << SCU_PADCTRL_X_LED_PWM1_POS)
#define SCU_PADCTRL_X_LED_PWM0_REG     SCU_PADCTRL6
#define SCU_PADCTRL_X_LED_PWM0_POS     (24)
#define SCU_PADCTRL_X_LED_PWM0_MSK     (0xFul << SCU_PADCTRL_X_LED_PWM0_POS)
#define SCU_PADCTRL_X_I2S1_SOUT_REG    SCU_PADCTRL6
#define SCU_PADCTRL_X_I2S1_SOUT_POS    (20)
#define SCU_PADCTRL_X_I2S1_SOUT_MSK    (0xFul << SCU_PADCTRL_X_I2S1_SOUT_POS)
#define SCU_PADCTRL_X_I2S1_SIN_REG     SCU_PADCTRL6
#define SCU_PADCTRL_X_I2S1_SIN_POS     (16)
#define SCU_PADCTRL_X_I2S1_SIN_MSK     (0xFul << SCU_PADCTRL_X_I2S1_SIN_POS)
#define SCU_PADCTRL_X_I2S1_BCLK_REG    SCU_PADCTRL6
#define SCU_PADCTRL_X_I2S1_BCLK_POS    (12)
#define SCU_PADCTRL_X_I2S1_BCLK_MSK    (0xFul << SCU_PADCTRL_X_I2S1_BCLK_POS)
#define SCU_PADCTRL_X_I2S1_WS_REG      SCU_PADCTRL6
#define SCU_PADCTRL_X_I2S1_WS_POS      (8)
#define SCU_PADCTRL_X_I2S1_WS_MSK      (0xFul << SCU_PADCTRL_X_I2S1_WS_POS)
#define SCU_PADCTRL_X_I2S0_MCLK_REG    SCU_PADCTRL6
#define SCU_PADCTRL_X_I2S0_MCLK_POS    (4)
#define SCU_PADCTRL_X_I2S0_MCLK_MSK    (0xFul << SCU_PADCTRL_X_I2S0_MCLK_POS)
#define SCU_PADCTRL_X_I2S0_SD_REG      SCU_PADCTRL6
#define SCU_PADCTRL_X_I2S0_SD_POS      (0)
#define SCU_PADCTRL_X_I2S0_SD_MSK      (0xFul << SCU_PADCTRL_X_I2S0_SD_POS)
#define SCU_PADCTRL_X_SPI2_CSB0_REG    SCU_PADCTRL7
#define SCU_PADCTRL_X_SPI2_CSB0_POS    (28)
#define SCU_PADCTRL_X_SPI2_CSB0_MSK    (0xFul << SCU_PADCTRL_X_SPI2_CSB0_POS)
#define SCU_PADCTRL_X_SPI2_SDO_REG     SCU_PADCTRL7
#define SCU_PADCTRL_X_SPI2_SDO_POS     (24)
#define SCU_PADCTRL_X_SPI2_SDO_MSK     (0xFul << SCU_PADCTRL_X_SPI2_SDO_POS)
#define SCU_PADCTRL_X_SPI2_SDI_REG     SCU_PADCTRL7
#define SCU_PADCTRL_X_SPI2_SDI_POS     (20)
#define SCU_PADCTRL_X_SPI2_SDI_MSK     (0xFul << SCU_PADCTRL_X_SPI2_SDI_POS)
#define SCU_PADCTRL_X_SPI2_SCK_REG     SCU_PADCTRL7
#define SCU_PADCTRL_X_SPI2_SCK_POS     (16)
#define SCU_PADCTRL_X_SPI2_SCK_MSK     (0xFul << SCU_PADCTRL_X_SPI2_SCK_POS)
#define SCU_PADCTRL_X_PDM0_DIN_REG     SCU_PADCTRL7
#define SCU_PADCTRL_X_PDM0_DIN_POS     (12)
#define SCU_PADCTRL_X_PDM0_DIN_MSK     (0xFul << SCU_PADCTRL_X_PDM0_DIN_POS)
#define SCU_PADCTRL_X_PDM0_CLK_REG     SCU_PADCTRL7
#define SCU_PADCTRL_X_PDM0_CLK_POS     (8)
#define SCU_PADCTRL_X_PDM0_CLK_MSK     (0xFul << SCU_PADCTRL_X_PDM0_CLK_POS)
#define SCU_PADCTRL_X_LED_PWM3_REG     SCU_PADCTRL7
#define SCU_PADCTRL_X_LED_PWM3_POS     (4)
#define SCU_PADCTRL_X_LED_PWM3_MSK     (0xFul << SCU_PADCTRL_X_LED_PWM3_POS)
#define SCU_PADCTRL_X_LED_PWM2_REG     SCU_PADCTRL7
#define SCU_PADCTRL_X_LED_PWM2_POS     (0)
#define SCU_PADCTRL_X_LED_PWM2_MSK     (0xFul << SCU_PADCTRL_X_LED_PWM2_POS)
#define SCU_PADCTRL_X_IMAGE_DI7_REG    SCU_PADCTRL8
#define SCU_PADCTRL_X_IMAGE_DI7_POS    (28)
#define SCU_PADCTRL_X_IMAGE_DI7_MSK    (0xFul << SCU_PADCTRL_X_IMAGE_DI7_POS)
#define SCU_PADCTRL_X_IMAGE_DI6_REG    SCU_PADCTRL8
#define SCU_PADCTRL_X_IMAGE_DI6_POS    (24)
#define SCU_PADCTRL_X_IMAGE_DI6_MSK    (0xFul << SCU_PADCTRL_X_IMAGE_DI6_POS)
#define SCU_PADCTRL_X_IMAGE_DI5_REG    SCU_PADCTRL8
#define SCU_PADCTRL_X_IMAGE_DI5_POS    (20)
#define SCU_PADCTRL_X_IMAGE_DI5_MSK    (0xFul << SCU_PADCTRL_X_IMAGE_DI5_POS)
#define SCU_PADCTRL_X_IMAGE_DI4_REG    SCU_PADCTRL8
#define SCU_PADCTRL_X_IMAGE_DI4_POS    (16)
#define SCU_PADCTRL_X_IMAGE_DI4_MSK    (0xFul << SCU_PADCTRL_X_IMAGE_DI4_POS)
#define SCU_PADCTRL_X_IMAGE_DI3_REG    SCU_PADCTRL8
#define SCU_PADCTRL_X_IMAGE_DI3_POS    (12)
#define SCU_PADCTRL_X_IMAGE_DI3_MSK    (0xFul << SCU_PADCTRL_X_IMAGE_DI3_POS)
#define SCU_PADCTRL_X_IMAGE_DI2_REG    SCU_PADCTRL8
#define SCU_PADCTRL_X_IMAGE_DI2_POS    (8)
#define SCU_PADCTRL_X_IMAGE_DI2_MSK    (0xFul << SCU_PADCTRL_X_IMAGE_DI2_POS)
#define SCU_PADCTRL_X_IMAGE_DI1_REG    SCU_PADCTRL8
#define SCU_PADCTRL_X_IMAGE_DI1_POS    (4)
#define SCU_PADCTRL_X_IMAGE_DI1_MSK    (0xFul << SCU_PADCTRL_X_IMAGE_DI1_POS)
#define SCU_PADCTRL_X_IMAGE_DI0_REG    SCU_PADCTRL8
#define SCU_PADCTRL_X_IMAGE_DI0_POS    (0)
#define SCU_PADCTRL_X_IMAGE_DI0_MSK    (0xFul << SCU_PADCTRL_X_IMAGE_DI0_POS)
#define SCU_PADCTRL_X_IMAGE_MCLK_REG   SCU_PADCTRL9
#define SCU_PADCTRL_X_IMAGE_MCLK_POS   (12)
#define SCU_PADCTRL_X_IMAGE_MCLK_MSK   (0xFul << SCU_PADCTRL_X_IMAGE_MCLK_POS)
#define SCU_PADCTRL_X_IMAGE_PCLK_REG   SCU_PADCTRL9
#define SCU_PADCTRL_X_IMAGE_PCLK_POS   (8)
#define SCU_PADCTRL_X_IMAGE_PCLK_MSK   (0xFul << SCU_PADCTRL_X_IMAGE_PCLK_POS)
#define SCU_PADCTRL_X_IMAGE_VSYNC_REG  SCU_PADCTRL9
#define SCU_PADCTRL_X_IMAGE_VSYNC_POS  (4)
#define SCU_PADCTRL_X_IMAGE_VSYNC_MSK  (0xFul << SCU_PADCTRL_X_IMAGE_VSYNC_POS)
#define SCU_PADCTRL_X_IMAGE_HSYNC_REG  SCU_PADCTRL9
#define SCU_PADCTRL_X_IMAGE_HSYNC_POS  (0)
#define SCU_PADCTRL_X_IMAGE_HSYNC_MSK  (0xFul << SCU_PADCTRL_X_IMAGE_HSYNC_POS)
#define SCU_DSI_HOST_REG               SCU_DCDBIB
#define SCU_DSI_HOST_POS               (0)
#define SCU_DSI_HOST_MSK               (0x1ul << SCU_DSI_HOST_POS)
#define SCU_TPULLZ_REG                 SCU_MIPILDO
#define SCU_TPULLZ_POS                 (6)
#define SCU_TPULLZ_MSK                 (0x1ul << SCU_TPULLZ_POS)
#define SCU_EN_REG                     SCU_MIPILDO
#define SCU_EN_POS                     (5)
#define SCU_EN_MSK                     (0x1ul << SCU_EN_POS)
#define SCU_TRIMVR_REG                 SCU_MIPILDO
#define SCU_TRIMVR_POS                 (1)
#define SCU_TRIMVR_MSK                 (0xFul << SCU_TRIMVR_POS)
#define SCU_SELTRMMVR_REG              SCU_MIPILDO
#define SCU_SELTRMMVR_POS              (0)
#define SCU_SELTRMMVR_MSK              (0x1ul << SCU_SELTRMMVR_POS)
#define SCU_XRST_PMA_REG               SCU_MIPIDPHY
#define SCU_XRST_PMA_POS               (1)
#define SCU_XRST_PMA_MSK               (0x1ul << SCU_XRST_PMA_POS)
#define SCU_PD_REG                     SCU_MIPIDPHY
#define SCU_PD_POS                     (0)
#define SCU_PD_MSK                     (0x1ul << SCU_PD_POS)
#define SCU_I2C4_REG                   SCU_I2CBUFAON
#define SCU_I2C4_POS                   (4)
#define SCU_I2C4_MSK                   (0x1ul << SCU_I2C4_POS)
#define SCU_I2C3_REG                   SCU_I2CBUFAON
#define SCU_I2C3_POS                   (3)
#define SCU_I2C3_MSK                   (0x1ul << SCU_I2C3_POS)
#define SCU_I2C2_REG                   SCU_I2CBUFAON
#define SCU_I2C2_POS                   (2)
#define SCU_I2C2_MSK                   (0x1ul << SCU_I2C2_POS)
#define SCU_I2C1_REG                   SCU_I2CBUFAON
#define SCU_I2C1_POS                   (1)
#define SCU_I2C1_MSK                   (0x1ul << SCU_I2C1_POS)
#define SCU_I2C0_REG                   SCU_I2CBUFAON
#define SCU_I2C0_POS                   (0)
#define SCU_I2C0_MSK                   (0x1ul << SCU_I2C0_POS)
