/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include <string.h>

#include "bootutil/sign_key.h"
#include "mcuboot_config/mcuboot_config.h"

#ifndef MCUBOOT_HW_KEY
    /* Signatures */
    #if defined(MCUBOOT_SIGN_RSA)
        #error MCUBOOT_SIGN_RSA is not supported yet.
        #define HAVE_KEYS
        const unsigned char rsa_pub_key[];
        const unsigned int rsa_pub_key_len;

    #elif defined(MCUBOOT_SIGN_EC256)
        #define HAVE_KEYS
        /* Autogenerated by imgtool.py, do not edit. */
        const unsigned char ecdsa_pub_key[] = {
            0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86,
            0x48, 0xce, 0x3d, 0x02, 0x01, 0x06, 0x08, 0x2a,
            0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x03,
            0x42, 0x00, 0x04, 0x63, 0xfc, 0x40, 0x84, 0x05,
            0x3e, 0xf4, 0x2f, 0x20, 0x56, 0xe5, 0xef, 0x8e,
            0x24, 0x96, 0xaf, 0xff, 0x4a, 0xe8, 0x6e, 0x76,
            0xd7, 0x68, 0xab, 0xda, 0x12, 0x46, 0xa7, 0x5a,
            0x9e, 0x57, 0x4b, 0x0a, 0x99, 0x57, 0x6d, 0x7a,
            0xfc, 0x93, 0xa0, 0x44, 0x1a, 0x6b, 0x7e, 0x5a,
            0xbf, 0x35, 0xc7, 0xaf, 0xa2, 0x19, 0xd3, 0x3d,
            0x41, 0x73, 0x81, 0x8e, 0x5c, 0x16, 0x79, 0x98,
            0xb6, 0x43, 0x92,
        };
        const unsigned int ecdsa_pub_key_len = 91;

    #elif defined(MCUBOOT_SIGN_ED25519)
        #error MCUBOOT_SIGN_ED25519 is not supported yet.
        #define HAVE_KEYS
        const unsigned char ed25519_pub_key[];
        const unsigned int ed25519_pub_key_len;
    #endif

    /* HAVE_KEYS */
    #ifdef HAVE_KEYS
        const struct bootutil_key bootutil_keys[] = {
            {
    #if defined(MCUBOOT_SIGN_RSA)
                .key = rsa_pub_key,
                .len = &rsa_pub_key_len,
    #elif defined(MCUBOOT_SIGN_EC256)
                .key = ecdsa_pub_key,
                .len = &ecdsa_pub_key_len,
    #elif defined(MCUBOOT_SIGN_ED25519)
                .key = ed25519_pub_key,
                .len = &ed25519_pub_key_len,
    #endif
            },
        };
        const int bootutil_key_cnt = 1;
    #endif
#else /* defined(MCUBOOT_HW_KEY) */
    unsigned int pub_key_len;
    struct bootutil_key bootutil_keys[1] = {
        {
            .key = 0,
            .len = &pub_key_len,
        }
    };
    const int bootutil_key_cnt = 1;

    /* Autogenerated by imgtool.py, do not edit. */
    static const unsigned char ecdsa_pub_key_hash[] = {
        0xc9, 0x68, 0xc8, 0x3b, 0xa6, 0x31, 0x88, 0xc3,
        0x6b, 0x86, 0x10, 0x08, 0x2e, 0xbd, 0x01, 0x57,
        0xc9, 0x1c, 0x07, 0x4d, 0xc8, 0x94, 0xf7, 0xce,
        0x13, 0x9f, 0x07, 0x12, 0x48, 0xc4, 0x54, 0xa6,
    };
    static const unsigned int ecdsa_pub_key_hash_len = 32;

    int boot_retrieve_public_key_hash(uint8_t image_index,
                                      uint8_t *public_key_hash,
                                      size_t *key_hash_size) {
        if (image_index != 0) {
            return -1; // Only support image 0
        }

        memcpy(public_key_hash, ecdsa_pub_key_hash, ecdsa_pub_key_hash_len);
        *key_hash_size = ecdsa_pub_key_hash_len;
        return 0;
    }
#endif /* !MCUBOOT_HW_KEY */

/* Encrypted Images */
#ifdef MCUBOOT_ENC_IMAGES
    /* Key Types */
    #if defined(MCUBOOT_ENCRYPT_RSA)
        #error "MCUBOOT_ENCRYPT_RSA is not supported yet."
        const unsigned char enc_priv_key[];
        const unsigned int enc_priv_key_len;

    #elif defined(MCUBOOT_ENCRYPT_EC256)
        /* Autogenerated by imgtool.py, do not edit. */
        const unsigned char enc_priv_key[] = {
            0x30, 0x81, 0x87, 0x02, 0x01, 0x00, 0x30, 0x13,
            0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02,
            0x01, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d,
            0x03, 0x01, 0x07, 0x04, 0x6d, 0x30, 0x6b, 0x02,
            0x01, 0x01, 0x04, 0x20, 0x8f, 0x58, 0x5c, 0x64,
            0xe1, 0xc6, 0xbd, 0xa7, 0xfc, 0x65, 0x2a, 0x6d,
            0xd4, 0xbd, 0x0e, 0x82, 0xcc, 0xd6, 0x97, 0x79,
            0x0c, 0xd0, 0x47, 0x9e, 0x9f, 0xa8, 0x6b, 0x15,
            0x08, 0x28, 0x3a, 0xf1, 0xa1, 0x44, 0x03, 0x42,
            0x00, 0x04, 0xf1, 0x09, 0x8a, 0xfc, 0xee, 0x48,
            0x59, 0xfc, 0xb7, 0x9c, 0xde, 0xdc, 0x94, 0x69,
            0x3c, 0x5c, 0x95, 0x7b, 0xb1, 0x7c, 0x02, 0x1a,
            0x67, 0x8b, 0x97, 0x16, 0x3d, 0x44, 0xe2, 0xf5,
            0xfc, 0x67, 0xa5, 0x78, 0x5f, 0xe9, 0xc7, 0xd3,
            0xeb, 0x16, 0x1b, 0x9e, 0x12, 0x14, 0xfa, 0xba,
            0xfe, 0xc4, 0x40, 0xd0, 0xc6, 0x4b, 0x18, 0x69,
            0x26, 0x58, 0xba, 0x8d, 0x72, 0x5e, 0x29, 0x9d,
            0x9c, 0x81,
        };
        const unsigned int enc_priv_key_len = 138;

    #elif defined(MCUBOOT_ENCRYPT_X25519)
        #error "MCUBOOT_ENCRYPT_X25519 is not supported yet."
        const unsigned char enc_priv_key[];
        const unsigned int enc_priv_key_len;

    #elif defined(MCUBOOT_ENCRYPT_KW)
        #error "MCUBOOT_ENCRYPT_KW is not supported yet."
        const unsigned char enc_priv_key[];
        const unsigned int enc_priv_key_len;

    #endif

    const struct bootutil_key bootutil_enc_key = {
        .key = enc_priv_key,
        .len = &enc_priv_key_len,
    };
#endif
