/**
 * @file      pufs_sp38e_regs.h
 * @brief     PUFsecurity SP38E register definition
 * @copyright 2020 PUFsecurity
 */
/* THIS SOFTWARE IS SUPPLIED BY PUFSECURITY ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. TO THE FULLEST
 * EXTENT ALLOWED BY LAW, PUFSECURITY'S TOTAL LIABILITY ON ALL CLAIMS IN
 * ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES,
 * IF ANY, THAT YOU HAVE PAID DIRECTLY TO PUFSECURITY FOR THIS SOFTWARE.
 */

#ifndef PUFS_SP38E_REGS_H
#define PUFS_SP38E_REGS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct pufs_sp38e_regs {
    volatile uint32_t version;
    volatile uint32_t interrupt;
    volatile uint32_t feature;
    uint32_t _pad1;
    volatile uint32_t status;
    uint32_t _pad2;
    volatile uint32_t cfg;
} pufs_sp38e_regs_Type;

#define SP38E_INTRPT_INTRPT_ST_MASK     0x00000001
#define SP38E_INTRPT_INTRPT_EN_MASK     0x00010000
#define SP38E_STATUS_BUSY_MASK          0x00000001
#define SP38E_STATUS_RESP_MASK          0xfffffffe
#define SP38E_CFG_BC_TYPE_MASK          0x00000003
#define SP38E_CFG_TWK_EN_MASK           0x00000004
#define SP38E_CFG_ENCRYPT_MASK          0x00000008
#define SP38E_CFG_SEQ_NUM_MASK          0x0fffff00

#ifdef __cplusplus
} // Closing brace for extern "C".
#endif

#endif /* PUFS_SP38E_REGS_H */
