/**
 * @file      memory_map.h
 * @brief     memory map of PUFsecurity IP modules
 * @copyright 2021 PUFsecurity
 * 
 * THIS SOFTWARE IS SUPPLIED BY PUFSECURITY ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. TO THE FULLEST
 * EXTENT ALLOWED BY LAW, PUFSECURITY'S TOTAL LIABILITY ON ALL CLAIMS IN
 * ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES,
 * IF ANY, THAT YOU HAVE PAID DIRECTLY TO PUFSECURITY FOR THIS SOFTWARE.
 */

#ifndef PUFS_MEMORY_MAP_H
#define PUFS_MEMORY_MAP_H

#ifdef __cplusplus
extern "C" {
#endif
#include "metal-platform.h"

#define PUFIOT_ADDR_START		METAL_UP_PUFOTP_200B0000_BASE_ADDRESS
#define PUFIOT_MAP_SIZE           0x5000

#define DMA_ADDR_OFFSET            0x000
#define CRYPTO_ADDR_OFFSET         0x100
#define SP38A_ADDR_OFFSET          0x200
#define CMAC_ADDR_OFFSET           0x220
#define SP38C_ADDR_OFFSET          0x240
#define SP38D_ADDR_OFFSET          0x260
#define SP38E_ADDR_OFFSET          0x280
#define KWP_ADDR_OFFSET            0x300
#define CHACHA_ADDR_OFFSET         0x400
#define HMAC_HASH_ADDR_OFFSET      0x800
#define KDF_ADDR_OFFSET            0x900
#define SP90A_ADDR_OFFSET          0xB00
#define KA_ADDR_OFFSET             0xC00
#define PKC_ADDR_OFFSET           0x1000
#define RT_ADDR_OFFSET            0x3000
#define RT_CDE_ADDR_OFFSET        0x4000

#define RESET_BASE_PHY_ADDR   0xF8000000
#define SW_RESET_OFFSET            0x240

# define PUFS_RT_TCM_BASE     0x43c10000

// FIXME: PUFS_RT_AUTOLOAD_BASE should be changed based on board env.
# define PUFS_RT_AUTOLOAD_BASE 0x50151000

#define PUFS_TEST_READ_ADDRESS 0x50151000
// The address MUST be changed based on board configuration.
#define PUFS_TEST_FIFO_ADDRESS 0x50150000

#ifdef __cplusplus
} // Closing brace for extern "C".
#endif

#endif /* PUFS_MEMORY_MAP_H */
