/**
 * @file      pufs_sp90a_regs.h
 * @brief     PUFsecurity SP90A register definition
 * @copyright 2020 PUFsecurity
 */
/* THIS SOFTWARE IS SUPPLIED BY PUFSECURITY ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. TO THE FULLEST
 * EXTENT ALLOWED BY LAW, PUFSECURITY'S TOTAL LIABILITY ON ALL CLAIMS IN
 * ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES,
 * IF ANY, THAT YOU HAVE PAID DIRECTLY TO PUFSECURITY FOR THIS SOFTWARE.
 */

#ifndef PUFS_SP90A_REGS_H
#define PUFS_SP90A_REGS_H

#ifdef __cplusplus
extern "C" {
#endif

#define PRE_SEED_LEN 48 ///< the byte length of SP90A_PRE_SEED_ADDR
#define RBITS_LEN 16 ///< the byte length of SP90A_RBITS_ADDR

typedef struct pufs_drbg_regs {
    volatile uint32_t version;
    volatile uint32_t interrupt;
    volatile uint32_t feature;
    uint32_t _pad1;
    volatile uint32_t status_0;
    volatile uint32_t status_1;
    volatile uint32_t test_mode;
    uint32_t _pad2;
    volatile uint32_t start;
    volatile uint32_t cfg;
    volatile uint32_t pre_seed[PRE_SEED_LEN/4];
    volatile uint32_t rbits[RBITS_LEN/4];
} pufs_drbg_regs_Type;

#define SP90A_INTRPT_INTRPT_ST_MASK     0x00000001
#define SP90A_INTRPT_INTRPT_EN_MASK     0x00010000
#define SP90A_FEATURE_CTR_DRBG_MASK     0x00000001
#define SP90A_FEATURE_HASH_DRBG_MASK    0x00000002
#define SP90A_FEATURE_HMAC_DRBG_MASK    0x00000004
#define SP90A_FEATURE_AES_128_MASK      0x20000000
#define SP90A_FEATURE_AES_192_MASK      0x40000000
#define SP90A_FEATURE_AES_256_MASK      0x80000000
#define SP90A_STATUS_0_BUSY_MASK        0x00000001
#define SP90A_STATUS_0_RESP_MASK        0xfffffffe
#define SP90A_STATUS_1_RBITS_VALID_MASK 0x0000000f
#define SP90A_STATUS_1_REQ_TOOLONG_MASK 0x00000010
#define SP90A_STATUS_1_RESEED_MASK      0x00000020
#define SP90A_STATUS_1_TEST_MODE_MASK   0x00000080
#define SP90A_STATUS_1_KEY_LEN_MASK     0x00000300
#define SP90A_STATUS_1_INSTANT_MASK     0x00030000
#define SP90A_CFG_BC_TYPE_MASK          0x00000003
#define SP90A_CFG_DRBG_FUNC_MASK        0x00000700
#define SP90A_CFG_DF_MASK               0x01000000

#ifdef __cplusplus
} // Closing brace for extern "C".
#endif

#endif /* PUFS_SP90A_REGS_H */
